import type { TechnicalArticle } from "@/lib/technical-articles";

const publishedAt = "2026-07-17";
const reviewedAt = "2026-07-22";
const ncfSelectionReviewedAt = "2026-07-27";

const ncfSources = [
  {
    title: "300gsm Biaxial Carbon Fiber Fabric TDS",
    publisher: "FRP HOME",
    url: "https://www.myfrphome.com/downloads/tds/FRP-HOME-300gsm-Biaxial-Carbon-Fabric-TDS.pdf",
  },
  {
    title: "600gsm +45°/-45° Biaxial Carbon NCF TDS",
    publisher: "FRP HOME",
    url: "https://www.myfrphome.com/downloads/tds/FRP-HOME-600gsm-PlusMinus45-Biaxial-Carbon-NCF-TDS.pdf",
  },
];

const laminateSources = [
  {
    title: "3K Carbon Fiber Laminate Sheet Product Specification & RFQ Guide",
    publisher: "FRP HOME",
    url: "https://www.myfrphome.com/downloads/specifications/FRP-HOME-3K-Carbon-Fiber-Laminate-Sheet-RFQ-Specification-Guide.pdf",
  },
];

export const dualCoreTechnicalArticles: TechnicalArticle[] = [
  {
    slug: "300gsm-vs-600gsm-biaxial-carbon-ncf",
    title: "300gsm vs 600gsm Biaxial Carbon NCF Selection Guide",
    description: "Compare verified 300gsm and 600gsm biaxial carbon NCF by orientation, layer weight, roll format, stitching and RFQ requirements.",
    image: "/images/products/carbon-fiber-multiaxial-ncf-fabric.webp",
    quickAnswer: "Choose 300gsm or 600gsm biaxial carbon NCF from the approved laminate schedule, not from gsm alone. The documented 300gsm family has two 150 g/m² carbon layers in +45°/-45° or 0°/90° constructions. The documented 600gsm product has two 300 g/m² carbon layers in a balanced +45°/-45° construction. The heavier format may reduce ply count, while the lighter format allows finer ply-by-ply control; both require process validation.",
    definition: "Biaxial carbon non-crimp fabric holds two substantially straight directional carbon layers together with lightweight stitching. The gsm value in this guide is the nominal carbon-fiber areal weight before resin. Total dry-fabric weight also includes stitch yarn, and neither dry-fabric value is a cured-laminate mechanical property.",
    comparison: {
      columns: ["Selection point", "300gsm biaxial NCF", "600gsm biaxial NCF"],
      rows: [
        ["Documented orientation", "+45°/-45° or 0°/90°", "Balanced +45°/-45°"],
        ["Carbon layer split", "150 + 150 g/m²", "300 + 300 g/m²"],
        ["Documented dry weight", "300 g/m² carbon; 308 g/m² total", "600 g/m² carbon; approximately 608-612 g/m² total"],
        ["Fiber and stitching", "Continuous 12K carbon; polyester 75D tricot stitch", "12K preferred, 24K by agreement; PES 75D or equivalent"],
        ["Published roll reference", "1270 mm x 50 m", "1270 mm x 50 m"],
        ["Laminate planning", "Finer ply increments; more plies may be required", "More reinforcement per ply; fewer plies may be possible"],
        ["Order control", "Use the 300gsm TDS tolerances and approved quotation", "Confirm tolerances, usable length, splice policy and COA scope in the order"],
      ],
    },
    selectionAdvice: [
      "Start with the engineer-approved load directions. The published 600gsm TDS supports +45°/-45° only; do not assume a documented 600gsm 0°/90° construction.",
      "Compare total ply count, layer sequence, cutting plan, placement time and drape rather than choosing from areal weight alone.",
      "Validate permeability, fill time, compaction and fiber-volume targets with the complete resin, core and consumable stack.",
      "Confirm carbon grade, sizing, stitch construction, width, roll length, splice policy, trial quantity and required COA items in the RFQ.",
      "Use the downloadable English TDS files as product references, then approve the final order specification and batch documents before production.",
    ],
    applications: [
      "Vacuum-infused panels",
      "RTM and VARTM components",
      "Shear webs and torsion shells",
      "Balanced 0°/90° panels using the documented 300gsm construction",
      "Industrial composite structures",
      "Automotive and marine composite parts",
    ],
    specifications: [
      ["300gsm documented scope", "FRPH-CBX300-X +45°/-45° and FRPH-CBX300-B 0°/90°"],
      ["600gsm documented scope", "FRPH-CBX600-45 balanced +45°/-45°"],
      ["Standard roll reference", "1270 mm width x 50 m roll; final tolerances follow the selected TDS and order"],
      ["Matrix review", "Epoxy, vinyl ester, unsaturated polyester, polyurethane or phenolic compatibility must be validated for the selected construction"],
      ["Process review", "Vacuum infusion, VARTM, RTM, wet lay-up, prepreg conversion or molding parameters require representative validation"],
      ["Performance boundary", "Dry-fabric data are not cured-laminate design allowables"],
    ],
    recommendedProducts: ["carbon-fiber-multiaxial-ncf-fabric"],
    rfqInformation: [
      "300gsm or 600gsm construction",
      "Exact fiber directions",
      "Carbon grade and sizing",
      "Total and per-layer areal weight",
      "Width and roll length",
      "Stitch construction",
      "Splice policy",
      "Resin and process",
      "Trial and production quantity",
      "COA requirements",
      "Destination and final application",
    ],
    faqs: [
      { question: "Is 600gsm biaxial NCF stronger than 300gsm NCF?", answer: "Areal weight alone does not determine final laminate strength. Fiber grade, orientation, ply count, resin, processing and laminate design all affect performance." },
      { question: "Is 600gsm 0°/90° carbon NCF covered by the published TDS?", answer: "No. The current published 600gsm TDS covers a balanced +45°/-45° construction. A 600gsm 0°/90° request requires separate construction and document confirmation." },
      { question: "Does 600gsm mean the total dry fabric weighs exactly 600 g/m²?", answer: "No. In the published 600gsm document, 600 g/m² is the nominal carbon-fiber basis. The typical total dry-fabric weight is approximately 608-612 g/m² including stitch yarn." },
      { question: "Can 300gsm and 600gsm NCF be used in one laminate?", answer: "They may be combined when the laminate design calls for it, but the complete stack, resin flow, compaction and cured laminate should be validated by the customer's technical team." },
    ],
    publishedAt,
    reviewedAt: ncfSelectionReviewedAt,
    sources: ncfSources,
  },
  {
    slug: "carbon-fiber-multiaxial-ncf-rfq-checklist",
    title: "Carbon Fiber Multiaxial NCF RFQ Checklist",
    description: "Prepare a complete RFQ for UD, biaxial, triaxial or quadriaxial carbon NCF with the directions, weight, width, stitch and resin process suppliers need.",
    image: "/images/products/carbon-fiber-multiaxial-ncf-fabric.webp",
    quickAnswer: "A useful carbon NCF RFQ identifies the architecture, fiber directions, areal weight, width, roll length, stitch, resin process, quantity, destination and final application. A product name such as 'biaxial carbon fabric' is not enough to confirm an order.",
    definition: "Multiaxial NCF is specified by its directional layers and stitched construction. UD, biaxial, triaxial and quadriaxial descriptions must be paired with the actual orientation and mass distribution required by the laminate design.",
    comparison: {
      columns: ["RFQ field", "Example input", "Why it matters"],
      rows: [
        ["Architecture", "Biaxial NCF", "Defines the number of directional layers"],
        ["Directions", "+45°/-45°", "Controls reinforcement orientation"],
        ["Areal weight", "300gsm or 600gsm", "Supports ply and roll planning"],
        ["Dimensions", "Width and roll length", "Supports cutting and packing review"],
        ["Process", "Vacuum infusion or RTM", "Guides construction and compatibility review"],
      ],
    },
    selectionAdvice: [
      "Attach the laminate schedule or drawing when possible.",
      "State whether the gsm value is total construction weight or a layer-specific requirement.",
      "Identify stitch material or handling requirements when they are design-controlled.",
      "Separate trial quantity from expected production volume.",
      "Provide final application and destination for compliance review.",
    ],
    applications: ["Composite sourcing", "Vacuum infusion trials", "RTM programs", "Panel production", "Drawing-based laminate development"],
    specifications: [
      ["Architecture", "UD / biaxial / triaxial / quadriaxial"],
      ["Direction notation", "0° / 90° / +45° / -45°"],
      ["Commercial details", "Width / roll length / quantity / destination"],
      ["Technical review", "Resin process / stack / final application"],
    ],
    recommendedProducts: ["carbon-fiber-multiaxial-ncf-fabric"],
    rfqInformation: ["Architecture", "Layer directions", "Total and layer gsm", "Width", "Roll length", "Stitch", "Resin and process", "Quantity", "Destination", "Final application"],
    faqs: [
      { question: "What does +45°/-45° mean on an NCF RFQ?", answer: "It describes two carbon layers oriented at positive and negative 45 degrees relative to the selected reference direction." },
      { question: "Should I request a sample first?", answer: "A representative trial can help confirm handling and processing before production, especially when the stack, resin or geometry is new." },
    ],
    publishedAt,
    reviewedAt,
    sources: ncfSources,
  },
  {
    slug: "biaxial-vs-triaxial-vs-quadriaxial-carbon-ncf",
    title: "Biaxial vs Triaxial vs Quadriaxial Carbon NCF",
    description: "Compare biaxial, triaxial and quadriaxial carbon NCF architectures by fiber direction, laminate planning and RFQ requirements.",
    image: "/images/products/carbon-fiber-multiaxial-ncf-fabric.webp",
    quickAnswer: "Biaxial NCF combines two directions, triaxial combines three, and quadriaxial combines four. The correct format follows the required load paths and laminate schedule; more directions are not automatically better.",
    definition: "NCF architecture describes how several directional carbon layers are assembled and stitched. Common direction sets include 0°/90°, +45°/-45°, 0°/+45°/-45° and 0°/+45°/90°/-45°, but every order must state its exact construction.",
    comparison: {
      columns: ["Architecture", "Direction example", "Procurement consideration"],
      rows: [
        ["Biaxial", "0°/90° or +45°/-45°", "Two-direction reinforcement and straightforward ply planning"],
        ["Triaxial", "0°/+45°/-45°", "Three-direction reinforcement in one stitched construction"],
        ["Quadriaxial", "0°/+45°/90°/-45°", "Four-direction reinforcement and a heavier combined layer"],
        ["Custom NCF", "Project-defined", "Requires complete layer and mass distribution details"],
      ],
    },
    selectionAdvice: [
      "Use the laminate engineer's load directions as the starting point.",
      "Compare combined-layer handling against the flexibility of separate plies.",
      "Confirm total gsm and the mass allocated to each direction.",
      "Validate drape, compaction and resin flow on representative geometry.",
    ],
    applications: ["Multidirectional panels", "Large composite structures", "Automotive CFRP", "Industrial shells", "Vacuum infusion and RTM"],
    specifications: [["Directions", "Project-defined 0° / 90° / +45° / -45°"], ["Construction", "Biaxial / triaxial / quadriaxial"], ["Order controls", "Layer mass / stitch / width / roll / resin process"]],
    recommendedProducts: ["carbon-fiber-multiaxial-ncf-fabric", "carbon-fiber-ud-fabric"],
    rfqInformation: ["Architecture", "Direction set", "Mass by layer", "Total gsm", "Width", "Roll length", "Stitch", "Process", "Quantity"],
    faqs: [
      { question: "Is quadriaxial NCF always more efficient than biaxial NCF?", answer: "No. Efficiency depends on required load directions, ply schedule, drape, process and part geometry." },
      { question: "Can the direction order be customized?", answer: "Project-defined constructions can be reviewed when the layer sequence, mass distribution, width, volume and process are provided." },
    ],
    publishedAt,
    reviewedAt,
    sources: ncfSources,
  },
  {
    slug: "carbon-fiber-plate-thickness-selection-guide",
    title: "Carbon Fiber Plate Thickness Selection Guide",
    description: "Select a 3K carbon fiber laminate sheet thickness by part geometry, layup, finish, tolerance and CNC requirements without confusing it with pultruded strengthening plate.",
    image: "/images/products/3k-carbon-fiber-laminate-sheet.webp",
    quickAnswer: "Plate thickness should follow the part design, support span, load case, layup, machining allowance and attachment method. Any available thickness, tolerance and layup must be confirmed in the drawing, quotation and approved order specification.",
    definition: "A 3K carbon fiber laminate sheet is a cured CFRP panel that can use visible 3K twill surface plies and project-defined inner reinforcement. It is different from a pultruded CFRP plate used in structural strengthening systems.",
    comparison: {
      columns: ["Decision", "Thin laminate", "Thicker laminate"],
      rows: [
        ["Typical buying reason", "Covers, skins and lightweight panels", "Brackets, fixtures and machined parts"],
        ["Design focus", "Flatness, handling and surface", "Layup, edge, holes and machining"],
        ["CNC review", "Clamping and edge protection", "Tool path, hole detail and tolerance"],
        ["Order confirmation", "Drawing and sample approval", "Drawing and sample approval"],
      ],
    },
    selectionAdvice: [
      "Provide a drawing and required thickness rather than selecting from appearance alone.",
      "Define whether the 3K twill surface is needed on one or both faces.",
      "Confirm matte, glossy, sanded or peel-ply finish before quotation.",
      "State flatness, thickness tolerance, holes, countersinks, edge condition and protective film needs.",
      "Keep structural strengthening plate specifications on the separate strengthening-system page.",
    ],
    applications: ["Industrial panels", "CNC brackets", "Equipment covers", "Automotive trim", "Sports and fixture components"],
    specifications: [["Surface", "3K twill by confirmed order"], ["Finish", "Matte / glossy / sanded / peel-ply by order"], ["Thickness", "Drawing and quotation controlled"], ["Layup", "Woven / UD / mixed, subject to technical review"]],
    recommendedProducts: ["3k-carbon-fiber-laminate-sheet", "custom-carbon-fiber-products"],
    rfqInformation: ["Drawing", "Length and width", "Thickness", "Tolerance", "Surface and finish", "Inner layup", "CNC details", "Quantity", "Final application"],
    faqs: [
      { question: "Is a thicker carbon plate always stiffer?", answer: "Geometry and thickness strongly affect stiffness, but the actual result also depends on fiber orientation, layup, resin, supports and load case. Engineering validation is required." },
      { question: "Is 3K laminate sheet the same as pultruded strengthening plate?", answer: "No. They use different product definitions, manufacturing routes and application controls and should not be substituted without engineering review." },
    ],
    publishedAt,
    reviewedAt,
    sources: laminateSources,
  },
  {
    slug: "3k-carbon-fiber-plate-cnc-rfq-guide",
    title: "3K Carbon Fiber Plate CNC and RFQ Guide",
    description: "Prepare drawings and RFQ details for CNC-cut 3K carbon fiber plate, including finish, holes, tolerances, edge treatment and quantity.",
    image: "/images/products/3k-carbon-fiber-laminate-stack.webp",
    quickAnswer: "For CNC 3K carbon plate, send a DXF, STEP or dimensioned drawing with material thickness, surface finish, hole and edge details, tolerances, quantity and final application. A reference photo alone is rarely enough for a production quotation.",
    definition: "CNC processing converts cured carbon laminate sheets into drawing-controlled parts. The laminate specification and the machining specification must be reviewed together because surface plies, edge exposure, hole geometry and tolerance influence production planning.",
    comparison: {
      columns: ["Input", "Minimum RFQ detail", "Review result"],
      rows: [
        ["Geometry", "DXF / STEP / dimensioned drawing", "Cut path and part nesting"],
        ["Material", "Thickness, size and layup requirement", "Suitable sheet definition"],
        ["Surface", "3K twill face and finish", "Appearance and protection plan"],
        ["Features", "Holes, slots, countersinks and edges", "Tooling and inspection plan"],
        ["Commercial", "Quantity, destination and use", "Quotation and compliance review"],
      ],
    },
    selectionAdvice: [
      "Mark appearance-critical faces on the drawing.",
      "Use explicit tolerances only where the assembly needs them.",
      "Specify hole diameter, countersink geometry and edge condition.",
      "Confirm protective film, labels and individual packing when surface quality matters.",
      "Approve a sample or first article when geometry or appearance is critical.",
    ],
    applications: ["CNC panels", "Brackets", "Fixtures", "Equipment components", "Drawing-based CFRP parts"],
    specifications: [["Drawing formats", "DXF / STEP / PDF drawing"], ["Surface options", "3K twill, matte or glossy by order"], ["Machining", "Cutting / drilling / slots / edge finishing by drawing"], ["Inspection", "Drawing-controlled dimensions agreed before production"]],
    recommendedProducts: ["3k-carbon-fiber-laminate-sheet", "custom-carbon-fiber-products"],
    rfqInformation: ["CAD or drawing", "Material thickness", "Surface face", "Finish", "Tolerance", "Hole and edge details", "Quantity", "Packing", "Final application"],
    faqs: [
      { question: "Can FRP HOME quote from a sample only?", answer: "A sample can support discussion, but a dimensioned drawing is preferred for tolerance, repeatability and inspection." },
      { question: "Should I specify matte or glossy before CNC cutting?", answer: "Yes. Surface finish and appearance-critical faces affect sheet selection, handling and protection." },
    ],
    publishedAt,
    reviewedAt,
    sources: laminateSources,
  },
  {
    slug: "matte-vs-glossy-3k-carbon-fiber-sheet",
    title: "Matte vs Glossy 3K Carbon Fiber Sheet",
    description: "Compare matte and glossy 3K carbon fiber sheet finishes for appearance, handling, machining and RFQ preparation.",
    image: "/images/products/3k-carbon-fiber-laminate-sheet.webp",
    quickAnswer: "Matte 3K sheet provides a restrained low-reflection appearance, while glossy sheet emphasizes weave depth and reflected light. Finish choice is visual and process-specific; it does not by itself define the laminate's structural performance.",
    definition: "Matte and glossy describe the exposed surface finish of a cured 3K carbon laminate. The visible weave, coating or surface treatment must be specified separately from thickness, inner layup and dimensional requirements.",
    comparison: {
      columns: ["Item", "Matte finish", "Glossy finish"],
      rows: [
        ["Appearance", "Low reflection and technical look", "High reflection and deeper visible weave"],
        ["Handling focus", "Avoid polishing marks and contamination", "Avoid scratches, haze and print-through"],
        ["RFQ detail", "Gloss level or approved sample", "Gloss level or approved sample"],
        ["Packing", "Surface protection by agreement", "Surface protection by agreement"],
      ],
    },
    selectionAdvice: [
      "Choose from the final assembly's lighting and appearance requirement.",
      "Use an approved physical sample when color, gloss or weave alignment is critical.",
      "State whether one face or both faces are appearance-controlled.",
      "Specify protective film and packing requirements for visible parts.",
    ],
    applications: ["Visible panels", "Automotive trim", "Equipment covers", "Sports products", "CNC appearance parts"],
    specifications: [["Visible reinforcement", "3K twill by order"], ["Finish", "Matte or glossy by approved specification"], ["Face requirement", "One-side or two-side appearance control"], ["Protection", "Film and packing by order review"]],
    recommendedProducts: ["3k-carbon-fiber-laminate-sheet"],
    rfqInformation: ["Matte or glossy", "Approved sample", "Appearance-controlled faces", "Thickness", "Panel size", "CNC drawing", "Quantity", "Packing"],
    faqs: [
      { question: "Is glossy carbon fiber sheet stronger than matte sheet?", answer: "Not because of gloss alone. Structural behavior depends on fiber, layup, resin, thickness, process and part design." },
      { question: "Can the finish be matched from a photo?", answer: "Photos help communication but lighting and displays vary. Use a physical approval sample for critical appearance matching." },
    ],
    publishedAt,
    reviewedAt,
    sources: laminateSources,
  },
];
