import type { ExtendedLocale } from "@/lib/i18n/config";
import type { UiCopy } from "@/lib/i18n/ui-copy";

const compliance = {
  ru: "Некоторые высокоэффективные углеродные материалы, препреги, нити, жгуты и компоненты CFRP требуют проверки конечного применения и конечного пользователя до предложения или отгрузки.",
  ar: "قد تتطلب بعض مواد ألياف الكربون عالية الأداء والمواد المسبقة التشريب والخيوط والحزم ومكونات CFRP مراجعة الاستخدام النهائي والمستخدم النهائي قبل العرض أو الشحن.",
  fr: "Certains matériaux carbone haute performance, préimprégnés, fils, mèches et composants CFRP peuvent nécessiter un examen de l'utilisation finale et de l'utilisateur final avant devis ou expédition.",
  ko: "일부 고성능 탄소섬유 소재, 프리프레그, 원사, 토우 및 CFRP 부품은 견적 또는 선적 전에 최종 용도와 최종 사용자 검토가 필요할 수 있습니다.",
  pl: "Niektóre wysokowydajne materiały z włókna węglowego, prepregi, przędze, tow i elementy CFRP mogą wymagać weryfikacji końcowego zastosowania i użytkownika przed ofertą lub wysyłką.",
  tr: "Bazı yüksek performanslı karbon elyaf malzemeler, prepregler, iplikler, tow ve CFRP bileşenleri teklif veya sevkiyattan önce nihai kullanım ve son kullanıcı incelemesi gerektirebilir.",
  uk: "Деякі високоефективні матеріали з вуглецевого волокна, препреги, пряжа, tow і компоненти CFRP можуть потребувати перевірки кінцевого використання та кінцевого користувача до надання пропозиції або відвантаження.",
  vi: "Một số vật liệu sợi carbon hiệu năng cao, prepreg, sợi, tow và chi tiết CFRP có thể cần được xem xét về mục đích sử dụng cuối cùng và người dùng cuối trước khi báo giá hoặc giao hàng.",
  th: "วัสดุคาร์บอนไฟเบอร์สมรรถนะสูงบางชนิด prepreg เส้นใย tow และชิ้นส่วน CFRP อาจต้องผ่านการตรวจสอบการใช้งานปลายทางและผู้ใช้ปลายทางก่อนเสนอราคาหรือจัดส่ง",
} satisfies Record<ExtendedLocale, string>;

export const extendedUiCopy: Record<ExtendedLocale, UiCopy> = {
  ru: {
    utility: { title: "Углеродные материалы и решения CFRP", meta: "B2B поставки композитных материалов" },
    nav: { home: "Главная", products: "Продукция", applications: "Применения", processes: "Процессы", technicalCenter: "Технический центр", quality: "Качество", about: "О компании", contact: "Контакты / RFQ" },
    productMenu: { title: "Продукция по группам материалов", description: "Выберите армирование, tow, prepreg, добавку, профиль или систему усиления." },
    footer: { company: "Компания", support: "Поддержка", contact: "Контакты", requestSample: "Запросить образец", description: "Армирующие материалы и композитные решения для стабильного производства, повторяемых характеристик и глобальных поставок." },
    language: { label: "Язык" },
    common: { requestQuote: "Запросить предложение", viewProducts: "Смотреть продукцию", viewProductPage: "Открыть страницу", viewAll: "Смотреть все", technicalCenter: "Технический центр", downloadCatalog: "Скачать каталог", sendInquiry: "Отправить запрос", quickAnswer: "Краткий ответ", specifications: "Характеристики", overview: "Обзор", applications: "Применения", faq: "Вопросы", documents: "Документы", endUseReview: "Проверка применения", relatedProducts: "Связанные продукты", complianceNotice: compliance.ru, brandAvailabilityNotice: "Доступность бренда зависит от запасов, партии, количества, страны назначения и проверки соответствия. Официальная авторизация не подразумевается без отдельного подтверждения.", documentsByScope: "TDS / SDS / COA в соответствии с продуктом и заказом", usuallyOneBusinessDay: "Обычно в течение одного рабочего дня" },
    rfq: { productType: "Тип продукта *", requestQuote: "Запросить предложение", fallbackIntro: "Базовая форма RFQ доступна до загрузки JavaScript.", name: "Имя *", company: "Компания *", email: "Email *", whatsapp: "WhatsApp / Телефон", country: "Страна", destinationCountry: "Страна назначения", endUse: "Конечное применение *", quantity: "Количество", requiredDocuments: "Необходимые документы", requiredSpecification: "Требуемый продукт / спецификация", fileUpload: "Загрузка файла", fileHelp: "Чертеж, спецификация или предыдущий TDS. Макс. {size} МБ.", details: "параметры", message: "Сообщение *", messagePlaceholder: "Укажите формат материала, процесс, применение, требования соответствия и срок.", endUseReview: "Проверка применения", urgentSupport: "Для срочного предложения напишите {email} или WhatsApp {whatsapp}.", submitNote: "Отправляя форму, вы соглашаетесь на связь по этому запросу.", submit: "Отправить RFQ", sending: "Отправка", successTitle: "Запрос получен.", successCopy: "Спасибо. Экспортная команда проверит требования и ответит в ближайшее время.", sendAnother: "Отправить новый запрос", errorCopy: "Не удалось отправить форму. Повторите попытку или напишите" },
  },
  ar: {
    utility: { title: "مواد ألياف الكربون وحلول CFRP", meta: "توريد مواد مركبة B2B" },
    nav: { home: "الرئيسية", products: "المنتجات", applications: "التطبيقات", processes: "العمليات", technicalCenter: "المركز التقني", quality: "الجودة", about: "عن الشركة", contact: "اتصال / طلب عرض" },
    productMenu: { title: "المنتجات حسب عائلة المادة", description: "اختر مواد التقوية أو tow أو prepreg أو الإضافات أو المقاطع أو نظام التقوية." },
    footer: { company: "الشركة", support: "الدعم", contact: "اتصل بنا", requestSample: "طلب عينة", description: "مواد تقوية وحلول مركبة لإنتاج مستقر وأداء متكرر وتسليم عالمي." },
    language: { label: "اللغة" },
    common: { requestQuote: "طلب عرض سعر", viewProducts: "عرض المنتجات", viewProductPage: "عرض صفحة المنتج", viewAll: "عرض الكل", technicalCenter: "المركز التقني", downloadCatalog: "تنزيل الكتالوج", sendInquiry: "إرسال استفسار", quickAnswer: "إجابة سريعة", specifications: "المواصفات", overview: "نظرة عامة", applications: "التطبيقات", faq: "الأسئلة الشائعة", documents: "المستندات", endUseReview: "مراجعة الاستخدام النهائي", relatedProducts: "منتجات ذات صلة", complianceNotice: compliance.ar, brandAvailabilityNotice: "يعتمد توفر العلامة على المخزون والدفعة والكمية وبلد الوجهة ومراجعة الامتثال. لا يعني ذلك تفويضاً رسمياً ما لم يذكر بشكل منفصل.", documentsByScope: "TDS / SDS / COA وفق نطاق المنتج واتفاق الطلب", usuallyOneBusinessDay: "عادة خلال يوم عمل واحد" },
    rfq: { productType: "نوع المنتج *", requestQuote: "طلب عرض سعر", fallbackIntro: "نموذج RFQ الأساسي متاح قبل تحميل JavaScript.", name: "الاسم *", company: "الشركة *", email: "البريد الإلكتروني *", whatsapp: "واتساب / هاتف", country: "الدولة", destinationCountry: "دولة الوجهة", endUse: "الاستخدام النهائي / التطبيق *", quantity: "الكمية", requiredDocuments: "المستندات المطلوبة", requiredSpecification: "المنتج / المواصفة المطلوبة", fileUpload: "رفع ملف", fileHelp: "رسم أو مواصفة أو TDS سابق. الحد {size} ميغابايت.", details: "التفاصيل", message: "الرسالة *", messagePlaceholder: "يرجى ذكر شكل المادة والعملية والتطبيق وسياق الامتثال والموعد.", endUseReview: "مراجعة الاستخدام النهائي", urgentSupport: "للدعم العاجل اكتب إلى {email} أو واتساب {whatsapp}.", submitNote: "بإرسال النموذج توافق على تواصلنا بشأن هذا الطلب.", submit: "إرسال RFQ", sending: "جارٍ الإرسال", successTitle: "تم استلام الاستفسار.", successCopy: "شكراً. سيراجع فريق التصدير متطلباتك ويرد قريباً.", sendAnother: "إرسال استفسار آخر", errorCopy: "تعذر إرسال النموذج. حاول مرة أخرى أو اكتب إلى" },
  },
  fr: {
    utility: { title: "Matériaux en fibre de carbone et solutions CFRP", meta: "Fourniture B2B de matériaux composites" },
    nav: { home: "Accueil", products: "Produits", applications: "Applications", processes: "Procédés", technicalCenter: "Centre technique", quality: "Qualité", about: "À propos", contact: "Contact / RFQ" },
    productMenu: { title: "Produits par famille de matériaux", description: "Choisissez par renfort, tow, prepreg, additif, profil ou système de renforcement." },
    footer: { company: "Entreprise", support: "Support", contact: "Contact", requestSample: "Demander un échantillon", description: "Matériaux de renfort et solutions composites pour une production stable, des performances répétables et une livraison mondiale." },
    language: { label: "Langue" },
    common: { requestQuote: "Demander un devis", viewProducts: "Voir les produits", viewProductPage: "Voir le produit", viewAll: "Voir tout", technicalCenter: "Centre technique", downloadCatalog: "Télécharger le catalogue", sendInquiry: "Envoyer une demande", quickAnswer: "Réponse rapide", specifications: "Spécifications", overview: "Aperçu", applications: "Applications", faq: "FAQ", documents: "Documents", endUseReview: "Examen de l'usage final", relatedProducts: "Produits associés", complianceNotice: compliance.fr, brandAvailabilityNotice: "La disponibilité des marques dépend du stock, du lot, de la quantité, du pays de destination et de l'examen de conformité. Aucune autorisation officielle n'est sous-entendue sans indication séparée.", documentsByScope: "TDS / SDS / COA selon le produit et l'accord de commande", usuallyOneBusinessDay: "Généralement sous un jour ouvré" },
    rfq: { productType: "Type de produit *", requestQuote: "Demander un devis", fallbackIntro: "Le formulaire RFQ de base reste visible avant le chargement de JavaScript.", name: "Nom *", company: "Société *", email: "Email *", whatsapp: "WhatsApp / Téléphone", country: "Pays", destinationCountry: "Pays de destination", endUse: "Usage final / Application *", quantity: "Quantité", requiredDocuments: "Documents requis", requiredSpecification: "Produit / spécification recherchée", fileUpload: "Ajouter un fichier", fileHelp: "Plan, spécification ou ancien TDS. Max. {size} Mo.", details: "détails", message: "Message *", messagePlaceholder: "Indiquez le format, le procédé, l'application, le contexte de conformité et le délai.", endUseReview: "Examen de l'usage final", urgentSupport: "Pour un devis urgent, écrivez à {email} ou WhatsApp {whatsapp}.", submitNote: "En envoyant, vous acceptez que nous vous contactions au sujet de cette demande.", submit: "Envoyer la RFQ", sending: "Envoi", successTitle: "Demande reçue.", successCopy: "Merci. Notre équipe export examinera vos besoins et répondra rapidement.", sendAnother: "Envoyer une autre demande", errorCopy: "Le formulaire n'a pas pu être envoyé. Réessayez ou écrivez à" },
  },
  ko: {
    utility: { title: "탄소섬유 소재 및 CFRP 솔루션", meta: "B2B 복합소재 공급" },
    nav: { home: "홈", products: "제품", applications: "적용 분야", processes: "공정", technicalCenter: "기술 센터", quality: "품질", about: "회사 소개", contact: "문의 / RFQ" },
    productMenu: { title: "소재군별 제품", description: "보강재, tow, prepreg, 첨가재, 프로파일 또는 구조 보강 시스템으로 선택하십시오." },
    footer: { company: "회사", support: "지원", contact: "문의", requestSample: "샘플 요청", description: "안정적인 생산, 반복 가능한 성능 및 글로벌 납품을 위한 보강재와 복합소재 솔루션." },
    language: { label: "언어" },
    common: { requestQuote: "견적 요청", viewProducts: "제품 보기", viewProductPage: "제품 페이지", viewAll: "전체 보기", technicalCenter: "기술 센터", downloadCatalog: "카탈로그 다운로드", sendInquiry: "문의 보내기", quickAnswer: "빠른 답변", specifications: "사양", overview: "개요", applications: "적용 분야", faq: "FAQ", documents: "문서", endUseReview: "최종 용도 검토", relatedProducts: "관련 제품", complianceNotice: compliance.ko, brandAvailabilityNotice: "브랜드 공급 여부는 재고, 배치, 수량, 도착 국가 및 규정 검토에 따라 달라집니다. 별도 명시가 없는 한 공식 권한을 의미하지 않습니다.", documentsByScope: "제품 범위와 주문 합의에 따른 TDS / SDS / COA", usuallyOneBusinessDay: "보통 영업일 1일 이내" },
    rfq: { productType: "제품 유형 *", requestQuote: "견적 요청", fallbackIntro: "기본 RFQ 양식은 JavaScript 로드 전에도 표시됩니다.", name: "이름 *", company: "회사 *", email: "이메일 *", whatsapp: "WhatsApp / 전화", country: "국가", destinationCountry: "도착 국가", endUse: "최종 용도 / 적용 분야 *", quantity: "수량", requiredDocuments: "필요 문서", requiredSpecification: "목표 제품 / 사양", fileUpload: "파일 업로드", fileHelp: "도면, 사양서 또는 이전 TDS. 최대 {size} MB.", details: "세부 사항", message: "메시지 *", messagePlaceholder: "소재 형식, 공정, 적용 분야, 규정 맥락 및 납기를 입력하십시오.", endUseReview: "최종 용도 검토", urgentSupport: "긴급 견적은 {email} 또는 WhatsApp {whatsapp}로 문의하십시오.", submitNote: "제출하면 이 요구 사항에 대해 연락하는 데 동의합니다.", submit: "RFQ 제출", sending: "전송 중", successTitle: "문의가 접수되었습니다.", successCopy: "감사합니다. 수출팀이 요구 사항을 검토하고 곧 회신하겠습니다.", sendAnother: "다른 문의 보내기", errorCopy: "양식을 전송하지 못했습니다. 다시 시도하거나 이메일로 문의하십시오" },
  },
  pl: {
    utility: { title: "Materiały z włókna węglowego i rozwiązania CFRP", meta: "Dostawy B2B materiałów kompozytowych" },
    nav: { home: "Strona główna", products: "Produkty", applications: "Zastosowania", processes: "Procesy", technicalCenter: "Centrum techniczne", quality: "Jakość", about: "O firmie", contact: "Kontakt / RFQ" },
    productMenu: { title: "Produkty według rodziny materiałów", description: "Wybierz zbrojenie, tow, prepreg, dodatek, profil lub system wzmacniania." },
    footer: { company: "Firma", support: "Wsparcie", contact: "Kontakt", requestSample: "Poproś o próbkę", description: "Materiały wzmacniające i rozwiązania kompozytowe dla stabilnej produkcji, powtarzalnych parametrów i globalnych dostaw." },
    language: { label: "Język" },
    common: { requestQuote: "Poproś o wycenę", viewProducts: "Zobacz produkty", viewProductPage: "Zobacz produkt", viewAll: "Zobacz wszystko", technicalCenter: "Centrum techniczne", downloadCatalog: "Pobierz katalog", sendInquiry: "Wyślij zapytanie", quickAnswer: "Szybka odpowiedź", specifications: "Specyfikacje", overview: "Przegląd", applications: "Zastosowania", faq: "FAQ", documents: "Dokumenty", endUseReview: "Weryfikacja zastosowania", relatedProducts: "Powiązane produkty", complianceNotice: compliance.pl, brandAvailabilityNotice: "Dostępność marki zależy od stanu magazynowego, partii, ilości, kraju docelowego i weryfikacji zgodności. Nie oznacza oficjalnej autoryzacji bez osobnego potwierdzenia.", documentsByScope: "TDS / SDS / COA zgodnie z zakresem produktu i zamówieniem", usuallyOneBusinessDay: "Zwykle w ciągu jednego dnia roboczego" },
    rfq: { productType: "Typ produktu *", requestQuote: "Poproś o wycenę", fallbackIntro: "Podstawowy formularz RFQ jest widoczny przed załadowaniem JavaScript.", name: "Imię i nazwisko *", company: "Firma *", email: "Email *", whatsapp: "WhatsApp / Telefon", country: "Kraj", destinationCountry: "Kraj docelowy", endUse: "Końcowe zastosowanie *", quantity: "Ilość", requiredDocuments: "Wymagane dokumenty", requiredSpecification: "Docelowy produkt / specyfikacja", fileUpload: "Dodaj plik", fileHelp: "Rysunek, specyfikacja lub poprzedni TDS. Maks. {size} MB.", details: "szczegóły", message: "Wiadomość *", messagePlaceholder: "Podaj format materiału, proces, zastosowanie, kontekst zgodności i termin.", endUseReview: "Weryfikacja zastosowania", urgentSupport: "Pilna wycena: {email} lub WhatsApp {whatsapp}.", submitNote: "Wysyłając formularz, zgadzasz się na kontakt w sprawie tego zapytania.", submit: "Wyślij RFQ", sending: "Wysyłanie", successTitle: "Zapytanie otrzymane.", successCopy: "Dziękujemy. Zespół eksportowy sprawdzi wymagania i wkrótce odpowie.", sendAnother: "Wyślij kolejne zapytanie", errorCopy: "Nie udało się wysłać formularza. Spróbuj ponownie lub napisz do" },
  },
  tr: {
    utility: { title: "Karbon fiber malzemeler ve CFRP çözümleri", meta: "B2B kompozit malzeme tedariki" },
    nav: { home: "Ana Sayfa", products: "Ürünler", applications: "Uygulamalar", processes: "Prosesler", technicalCenter: "Teknik Merkez", quality: "Kalite", about: "Hakkımızda", contact: "İletişim / RFQ" },
    productMenu: { title: "Malzeme ailesine göre ürünler", description: "Takviye, tow, prepreg, katkı, profil veya güçlendirme sistemi seçin." },
    footer: { company: "Şirket", support: "Destek", contact: "İletişim", requestSample: "Numune isteyin", description: "Kararlı üretim, tekrarlanabilir performans ve küresel teslimat için takviye malzemeleri ve kompozit çözümler." },
    language: { label: "Dil" },
    common: { requestQuote: "Teklif İste", viewProducts: "Ürünleri Gör", viewProductPage: "Ürün sayfası", viewAll: "Tümünü gör", technicalCenter: "Teknik Merkez", downloadCatalog: "Kataloğu İndir", sendInquiry: "Talep Gönder", quickAnswer: "Kısa Cevap", specifications: "Teknik Özellikler", overview: "Genel Bakış", applications: "Uygulamalar", faq: "SSS", documents: "Belgeler", endUseReview: "Nihai kullanım incelemesi", relatedProducts: "İlgili ürünler", complianceNotice: compliance.tr, brandAvailabilityNotice: "Marka bulunabilirliği stok, parti, miktar, hedef ülke ve uygunluk incelemesine bağlıdır. Ayrı olarak belirtilmedikçe resmi yetkilendirme anlamına gelmez.", documentsByScope: "Ürün kapsamı ve sipariş anlaşmasına göre TDS / SDS / COA", usuallyOneBusinessDay: "Genellikle bir iş günü içinde" },
    rfq: { productType: "Ürün Tipi *", requestQuote: "Teklif İste", fallbackIntro: "Temel RFQ formu JavaScript yüklenmeden önce de görünür.", name: "Ad *", company: "Şirket *", email: "E-posta *", whatsapp: "WhatsApp / Telefon", country: "Ülke", destinationCountry: "Hedef Ülke", endUse: "Nihai Kullanım / Uygulama *", quantity: "Miktar", requiredDocuments: "Gerekli Belgeler", requiredSpecification: "Hedef Ürün / Teknik Özellik", fileUpload: "Dosya Yükleme", fileHelp: "Çizim, teknik şartname veya önceki TDS. Maks. {size} MB.", details: "detaylar", message: "Mesaj *", messagePlaceholder: "Malzeme formatı, proses, uygulama, uygunluk bağlamı ve termin bilgisini ekleyin.", endUseReview: "Nihai kullanım incelemesi", urgentSupport: "Acil teklif için {email} veya WhatsApp {whatsapp} ile iletişime geçin.", submitNote: "Göndererek bu gereksinim hakkında sizinle iletişim kurmamızı kabul edersiniz.", submit: "RFQ Gönder", sending: "Gönderiliyor", successTitle: "Talep alındı.", successCopy: "Teşekkürler. İhracat ekibimiz gereksinimleri inceleyip kısa sürede yanıt verecektir.", sendAnother: "Başka talep gönder", errorCopy: "Form gönderilemedi. Tekrar deneyin veya e-posta gönderin" },
  },
  uk: {
    utility: { title: "Матеріали з вуглецевого волокна та рішення CFRP", meta: "B2B постачання композитних матеріалів" },
    nav: { home: "Головна", products: "Продукція", applications: "Застосування", processes: "Процеси", technicalCenter: "Технічний центр", quality: "Якість", about: "Про нас", contact: "Контакт / RFQ" },
    productMenu: { title: "Продукція за групами матеріалів", description: "Оберіть армування, tow, prepreg, добавку, профіль або систему підсилення." },
    footer: { company: "Компанія", support: "Підтримка", contact: "Контакти", requestSample: "Запитати зразок", description: "Армувальні матеріали та композитні рішення для стабільного виробництва, повторюваних властивостей і міжнародних поставок." },
    language: { label: "Мова" },
    common: { requestQuote: "Запросити пропозицію", viewProducts: "Переглянути продукцію", viewProductPage: "Сторінка продукту", viewAll: "Переглянути все", technicalCenter: "Технічний центр", downloadCatalog: "Завантажити каталог", sendInquiry: "Надіслати запит", quickAnswer: "Коротка відповідь", specifications: "Специфікації", overview: "Огляд", applications: "Застосування", faq: "Запитання", documents: "Документи", endUseReview: "Перевірка кінцевого використання", relatedProducts: "Пов’язані продукти", complianceNotice: compliance.uk, brandAvailabilityNotice: "Доступність бренду залежить від запасу, партії, кількості, країни призначення та перевірки відповідності. Офіційна авторизація не мається на увазі без окремого підтвердження.", documentsByScope: "TDS / SDS / COA відповідно до продукту та умов замовлення", usuallyOneBusinessDay: "Зазвичай протягом одного робочого дня" },
    rfq: { productType: "Тип продукту *", requestQuote: "Запросити пропозицію", fallbackIntro: "Базова форма RFQ доступна до завантаження JavaScript.", name: "Ім’я *", company: "Компанія *", email: "Email *", whatsapp: "WhatsApp / Телефон", country: "Країна", destinationCountry: "Країна призначення", endUse: "Кінцеве використання / застосування *", quantity: "Кількість", requiredDocuments: "Необхідні документи", requiredSpecification: "Потрібний продукт / специфікація", fileUpload: "Завантажити файл", fileHelp: "Креслення, специфікація або попередній TDS. Макс. {size} МБ.", details: "деталі", message: "Повідомлення *", messagePlaceholder: "Вкажіть формат матеріалу, процес, застосування, вимоги відповідності та термін.", endUseReview: "Перевірка кінцевого використання", urgentSupport: "Для термінової пропозиції напишіть {email} або WhatsApp {whatsapp}.", submitNote: "Надсилаючи форму, ви погоджуєтесь на зв’язок щодо цього запиту.", submit: "Надіслати RFQ", sending: "Надсилання", successTitle: "Запит отримано.", successCopy: "Дякуємо. Наша експортна команда перевірить вимоги та незабаром відповість.", sendAnother: "Надіслати інший запит", errorCopy: "Не вдалося надіслати форму. Спробуйте ще раз або напишіть" },
  },
  vi: {
    utility: { title: "Vật liệu sợi carbon và giải pháp CFRP", meta: "Cung ứng vật liệu composite B2B" },
    nav: { home: "Trang chủ", products: "Sản phẩm", applications: "Ứng dụng", processes: "Quy trình", technicalCenter: "Trung tâm kỹ thuật", quality: "Chất lượng", about: "Giới thiệu", contact: "Liên hệ / RFQ" },
    productMenu: { title: "Sản phẩm theo nhóm vật liệu", description: "Chọn theo vật liệu gia cường, tow, prepreg, phụ gia, profile hoặc hệ gia cường." },
    footer: { company: "Công ty", support: "Hỗ trợ", contact: "Liên hệ", requestSample: "Yêu cầu mẫu", description: "Vật liệu gia cường và giải pháp composite cho sản xuất ổn định, hiệu năng lặp lại và giao hàng toàn cầu." },
    language: { label: "Ngôn ngữ" },
    common: { requestQuote: "Yêu cầu báo giá", viewProducts: "Xem sản phẩm", viewProductPage: "Xem trang sản phẩm", viewAll: "Xem tất cả", technicalCenter: "Trung tâm kỹ thuật", downloadCatalog: "Tải catalog", sendInquiry: "Gửi yêu cầu", quickAnswer: "Trả lời nhanh", specifications: "Thông số kỹ thuật", overview: "Tổng quan", applications: "Ứng dụng", faq: "Câu hỏi thường gặp", documents: "Tài liệu", endUseReview: "Xem xét mục đích sử dụng cuối", relatedProducts: "Sản phẩm liên quan", complianceNotice: compliance.vi, brandAvailabilityNotice: "Tình trạng sẵn có của thương hiệu phụ thuộc vào tồn kho, lô hàng, số lượng, nước đến và việc xem xét tuân thủ. Không hàm ý ủy quyền chính thức nếu không được xác nhận riêng.", documentsByScope: "TDS / SDS / COA theo phạm vi sản phẩm và thỏa thuận đơn hàng", usuallyOneBusinessDay: "Thông thường trong một ngày làm việc" },
    rfq: { productType: "Loại sản phẩm *", requestQuote: "Yêu cầu báo giá", fallbackIntro: "Biểu mẫu RFQ cơ bản vẫn hiển thị trước khi JavaScript tải.", name: "Tên *", company: "Công ty *", email: "Email *", whatsapp: "WhatsApp / Điện thoại", country: "Quốc gia", destinationCountry: "Quốc gia đến", endUse: "Mục đích sử dụng cuối / ứng dụng *", quantity: "Số lượng", requiredDocuments: "Tài liệu yêu cầu", requiredSpecification: "Sản phẩm / thông số cần có", fileUpload: "Tải tệp", fileHelp: "Bản vẽ, thông số hoặc TDS trước đó. Tối đa {size} MB.", details: "chi tiết", message: "Nội dung *", messagePlaceholder: "Vui lòng nêu dạng vật liệu, quy trình, ứng dụng, bối cảnh tuân thủ và thời hạn.", endUseReview: "Xem xét mục đích sử dụng cuối", urgentSupport: "Để được báo giá gấp, gửi email {email} hoặc WhatsApp {whatsapp}.", submitNote: "Khi gửi biểu mẫu, bạn đồng ý để chúng tôi liên hệ về yêu cầu này.", submit: "Gửi RFQ", sending: "Đang gửi", successTitle: "Đã nhận yêu cầu.", successCopy: "Cảm ơn bạn. Đội ngũ xuất khẩu sẽ xem xét yêu cầu và phản hồi sớm.", sendAnother: "Gửi yêu cầu khác", errorCopy: "Không thể gửi biểu mẫu. Vui lòng thử lại hoặc gửi email đến" },
  },
  th: {
    utility: { title: "วัสดุคาร์บอนไฟเบอร์และโซลูชัน CFRP", meta: "การจัดหาวัสดุคอมโพสิตแบบ B2B" },
    nav: { home: "หน้าแรก", products: "ผลิตภัณฑ์", applications: "การใช้งาน", processes: "กระบวนการ", technicalCenter: "ศูนย์เทคนิค", quality: "คุณภาพ", about: "เกี่ยวกับเรา", contact: "ติดต่อ / RFQ" },
    productMenu: { title: "ผลิตภัณฑ์ตามกลุ่มวัสดุ", description: "เลือกวัสดุเสริมแรง tow prepreg สารเติมแต่ง โปรไฟล์ หรือระบบเสริมกำลัง" },
    footer: { company: "บริษัท", support: "สนับสนุน", contact: "ติดต่อ", requestSample: "ขอตัวอย่าง", description: "วัสดุเสริมแรงและโซลูชันคอมโพสิตสำหรับการผลิตที่สม่ำเสมอ คุณสมบัติที่ทำซ้ำได้ และการจัดส่งทั่วโลก" },
    language: { label: "ภาษา" },
    common: { requestQuote: "ขอใบเสนอราคา", viewProducts: "ดูผลิตภัณฑ์", viewProductPage: "ดูหน้าผลิตภัณฑ์", viewAll: "ดูทั้งหมด", technicalCenter: "ศูนย์เทคนิค", downloadCatalog: "ดาวน์โหลดแคตตาล็อก", sendInquiry: "ส่งคำถาม", quickAnswer: "คำตอบโดยย่อ", specifications: "ข้อมูลจำเพาะ", overview: "ภาพรวม", applications: "การใช้งาน", faq: "คำถามที่พบบ่อย", documents: "เอกสาร", endUseReview: "การตรวจสอบการใช้งานปลายทาง", relatedProducts: "ผลิตภัณฑ์ที่เกี่ยวข้อง", complianceNotice: compliance.th, brandAvailabilityNotice: "ความพร้อมของแบรนด์ขึ้นอยู่กับสต็อก ล็อต ปริมาณ ประเทศปลายทาง และการตรวจสอบการปฏิบัติตามข้อกำหนด ไม่ได้หมายถึงการอนุญาตอย่างเป็นทางการหากไม่มีการยืนยันแยกต่างหาก", documentsByScope: "TDS / SDS / COA ตามขอบเขตผลิตภัณฑ์และข้อตกลงการสั่งซื้อ", usuallyOneBusinessDay: "โดยปกติภายในหนึ่งวันทำการ" },
    rfq: { productType: "ประเภทผลิตภัณฑ์ *", requestQuote: "ขอใบเสนอราคา", fallbackIntro: "แบบฟอร์ม RFQ พื้นฐานจะแสดงก่อน JavaScript โหลด", name: "ชื่อ *", company: "บริษัท *", email: "อีเมล *", whatsapp: "WhatsApp / โทรศัพท์", country: "ประเทศ", destinationCountry: "ประเทศปลายทาง", endUse: "การใช้งานปลายทาง / การใช้งาน *", quantity: "ปริมาณ", requiredDocuments: "เอกสารที่ต้องการ", requiredSpecification: "ผลิตภัณฑ์ / ข้อมูลจำเพาะที่ต้องการ", fileUpload: "อัปโหลดไฟล์", fileHelp: "แบบร่าง ข้อมูลจำเพาะ หรือ TDS เดิม สูงสุด {size} MB", details: "รายละเอียด", message: "ข้อความ *", messagePlaceholder: "โปรดระบุรูปแบบวัสดุ กระบวนการ การใช้งาน ข้อกำหนดการปฏิบัติตาม และกำหนดเวลา", endUseReview: "การตรวจสอบการใช้งานปลายทาง", urgentSupport: "หากต้องการใบเสนอราคาเร่งด่วน โปรดอีเมล {email} หรือ WhatsApp {whatsapp}", submitNote: "เมื่อส่งแบบฟอร์ม คุณยินยอมให้เราติดต่อเกี่ยวกับความต้องการนี้", submit: "ส่ง RFQ", sending: "กำลังส่ง", successTitle: "ได้รับคำถามแล้ว", successCopy: "ขอบคุณ ทีมส่งออกของเราจะตรวจสอบความต้องการและตอบกลับโดยเร็ว", sendAnother: "ส่งคำถามอื่น", errorCopy: "ไม่สามารถส่งแบบฟอร์มได้ โปรดลองอีกครั้งหรืออีเมลถึง" },
  },
};

const productKeys = [
  "Woven Carbon Fiber Fabric",
  "Spread Tow Carbon Fiber Fabric",
  "UD Carbon Fiber Fabric",
  "Carbon Fiber Yarn & Tow",
  "Prepreg Carbon Fiber Materials",
  "Chopped Carbon Fiber",
  "Milled Carbon Fiber Powder",
  "Carbon Fiber Multiaxial NCF Fabric",
  "3K Carbon Fiber Laminate Sheet",
  "Structural Strengthening System",
  "Filament-Wound Carbon Fiber Tube",
  "Prepreg Carbon Fiber Fabric",
  "UD Carbon Fiber Fabric for Structural Strengthening",
  "Carbon Fiber for Plastic & Resin Reinforcement",
] as const;

const productValues: Record<ExtendedLocale, readonly string[]> = {
  ru: ["Ткань из углеродного волокна", "Углеродная ткань spread tow", "Однонаправленная углеродная ткань UD", "Углеродная нить и жгут (tow)", "Углеродные препреги", "Рубленое углеродное волокно", "Молотый порошок углеродного волокна", "Мультиаксиальная углеродная ткань NCF", "Лист и плита из углепластика 3K", "Система конструкционного усиления CFRP", "Углепластиковая труба филаментной намотки", "Углеродный препрег", "Ткань UD для конструкционного усиления", "Углеродное волокно для армирования пластика и смолы"],
  ar: ["نسيج ألياف الكربون المنسوج", "نسيج ألياف الكربون spread tow", "نسيج ألياف الكربون أحادي الاتجاه UD", "خيوط وحزم ألياف الكربون", "مواد ألياف الكربون المسبقة التشريب", "ألياف كربون مقطعة", "مسحوق ألياف كربون مطحون", "نسيج كربون متعدد المحاور NCF", "صفيحة ألياف كربون 3K", "نظام تقوية إنشائية CFRP", "أنبوب ألياف كربون باللف الخيطي", "نسيج كربوني مسبق التشريب", "نسيج UD للتقوية الإنشائية", "ألياف كربون لتقوية البلاستيك والراتنج"],
  fr: ["Tissu de fibre de carbone", "Tissu carbone spread tow", "Tissu carbone unidirectionnel UD", "Fil et tow de fibre de carbone", "Préimprégnés en fibre de carbone", "Fibre de carbone coupée", "Poudre de fibre de carbone broyée", "Tissu carbone multiaxial NCF", "Plaque stratifiée carbone 3K", "Système de renforcement structurel CFRP", "Tube carbone enroulé filamentaire", "Tissu carbone préimprégné", "Tissu UD pour renforcement structurel", "Fibre de carbone pour renfort de plastiques et résines"],
  ko: ["직조 탄소섬유 원단", "Spread tow 탄소섬유 원단", "UD 단방향 탄소섬유 원단", "탄소섬유 원사 및 tow", "탄소섬유 프리프레그", "단섬유 탄소섬유", "밀드 탄소섬유 분말", "다축 탄소섬유 NCF 원단", "3K 탄소섬유 적층판", "CFRP 구조 보강 시스템", "필라멘트 와인딩 탄소섬유 튜브", "탄소섬유 프리프레그 원단", "구조 보강용 UD 탄소섬유 원단", "플라스틱 및 수지 보강용 탄소섬유"],
  pl: ["Tkanina z włókna węglowego", "Tkanina węglowa spread tow", "Jednokierunkowa tkanina węglowa UD", "Przędza i tow z włókna węglowego", "Prepregi z włókna węglowego", "Cięte włókno węglowe", "Mielony proszek z włókna węglowego", "Multiaxialna tkanina węglowa NCF", "Płyta laminowana 3K z włókna węglowego", "System wzmocnienia konstrukcyjnego CFRP", "Rura z włókna węglowego nawijana filamentowo", "Prepreg z tkaniny węglowej", "Tkanina UD do wzmocnień konstrukcyjnych", "Włókno węglowe do wzmacniania tworzyw i żywic"],
  tr: ["Dokuma karbon fiber kumaş", "Spread tow karbon fiber kumaş", "UD tek yönlü karbon fiber kumaş", "Karbon fiber iplik ve tow", "Karbon fiber prepreg malzemeler", "Kırpılmış karbon fiber", "Öğütülmüş karbon fiber tozu", "Çok eksenli karbon fiber NCF kumaş", "3K karbon fiber laminat plaka", "CFRP yapısal güçlendirme sistemi", "Filament sarım karbon fiber tüp", "Karbon fiber prepreg kumaş", "Yapısal güçlendirme için UD karbon fiber kumaş", "Plastik ve reçine takviyesi için karbon fiber"],
  uk: ["Ткана вуглецева тканина", "Вуглецева тканина spread tow", "Односпрямована вуглецева тканина UD", "Вуглецева пряжа та tow", "Вуглецеві препреги", "Рубане вуглецеве волокно", "Мелений порошок вуглецевого волокна", "Мультиаксіальна вуглецева тканина NCF", "Ламінований лист вуглецевого волокна 3K", "Система конструкційного підсилення CFRP", "Вуглецева труба філаментного намотування", "Вуглецева тканина препрег", "Вуглецева тканина UD для підсилення", "Вуглецеве волокно для армування пластику та смол"],
  vi: ["Vải sợi carbon dệt", "Vải carbon spread tow", "Vải carbon UD một hướng", "Sợi và tow carbon", "Vật liệu prepreg sợi carbon", "Sợi carbon cắt ngắn", "Bột sợi carbon nghiền", "Vải carbon đa trục NCF", "Tấm laminate sợi carbon 3K", "Hệ gia cường kết cấu CFRP", "Ống sợi carbon quấn filament", "Vải prepreg carbon", "Vải carbon UD cho gia cường kết cấu", "Sợi carbon gia cường nhựa và resin"],
  th: ["ผ้าคาร์บอนไฟเบอร์ทอ", "ผ้าคาร์บอนไฟเบอร์ spread tow", "ผ้าคาร์บอนไฟเบอร์ UD ทิศทางเดียว", "เส้นใยและ tow คาร์บอน", "วัสดุ prepreg คาร์บอนไฟเบอร์", "คาร์บอนไฟเบอร์ตัดสั้น", "ผงคาร์บอนไฟเบอร์บด", "ผ้าคาร์บอนไฟเบอร์หลายแกน NCF", "แผ่นลามิเนตคาร์บอนไฟเบอร์ 3K", "ระบบเสริมกำลังโครงสร้าง CFRP", "ท่อคาร์บอนไฟเบอร์พันฟิลาเมนต์", "ผ้า prepreg คาร์บอน", "ผ้าคาร์บอนไฟเบอร์ UD สำหรับเสริมกำลัง", "คาร์บอนไฟเบอร์สำหรับเสริมพลาสติกและเรซิน"],
};

export const extendedProductTranslations = Object.fromEntries(
  Object.entries(productValues).map(([locale, values]) => [locale, Object.fromEntries(productKeys.map((key, index) => [key, values[index]]))]),
) as Record<ExtendedLocale, Record<string, string>>;

const familyValues: Record<ExtendedLocale, readonly [string, string][]> = {
  ru: [["Армирующие материалы из углеродного волокна", "Сухие ткани и текстильное армирование для композитов."], ["Углеродная нить, жгуты и исходные материалы", "Нить, жгут (tow), ровинг и PAN для дальнейшей переработки."], ["Углеродные препреги", "Пропитанные смолой материалы для контролируемого формования."], ["Рубленое и молотое углеродное волокно", "Короткое волокно и порошок для пластика и смол."], ["Профили CFRP и детали", "Трубы, пластины, стержни и детали с ЧПУ-обработкой."], ["Система конструкционного усиления", "Ткань UD, пластина CFRP и эпоксидная смола."]],
  ar: [["مواد تقوية ألياف الكربون", "أقمشة جافة وتقويات نسيجية للمواد المركبة."], ["خيوط وحزم ومواد أولية", "خيوط وtow وroving وPAN للتحويل اللاحق."], ["مواد كربونية مسبقة التشريب", "مواد مشربة بالراتنج للقولبة المضبوطة."], ["ألياف كربون مقطعة ومطحونة", "ألياف قصيرة ومسحوق للبلاستيك والراتنج."], ["مقاطع CFRP وقطع مخصصة", "أنابيب وصفائح وقضبان وقطع CNC."], ["نظام تقوية إنشائية", "نسيج UD وصفائح CFRP وراتنج إيبوكسي."]],
  fr: [["Renforts en fibre de carbone", "Tissus secs et renforts textiles pour composites."], ["Fil, tow et matières précurseurs", "Fil, tow, roving et PAN pour transformation."], ["Préimprégnés carbone", "Matériaux imprégnés de résine pour moulage contrôlé."], ["Fibre de carbone coupée et broyée", "Fibre courte et poudre pour plastiques et résines."], ["Profils CFRP et pièces sur mesure", "Tubes, plaques, tiges et pièces CNC."], ["Système de renforcement structurel", "Tissu UD, plaque CFRP et résine époxy."]],
  ko: [["탄소섬유 보강재", "복합재 제조용 건식 원단과 섬유 보강재."], ["탄소섬유 원사, tow 및 전구체", "후속 가공용 원사, tow, roving 및 PAN."], ["탄소섬유 프리프레그", "제어 성형용 수지 함침 소재."], ["단섬유 및 밀드 탄소섬유", "플라스틱과 수지용 단섬유 및 분말."], ["CFRP 프로파일 및 맞춤 부품", "튜브, 판, 봉 및 CNC 부품."], ["구조 보강 시스템", "UD 원단, CFRP 판 및 에폭시 수지."]],
  pl: [["Wzmocnienia z włókna węglowego", "Suche tkaniny i zbrojenia tekstylne do kompozytów."], ["Przędza, tow i materiały prekursorowe", "Przędza, tow, roving i PAN do dalszego przetwarzania."], ["Prepregi węglowe", "Materiały impregnowane żywicą do kontrolowanego formowania."], ["Cięte i mielone włókno węglowe", "Krótkie włókno i proszek do tworzyw i żywic."], ["Profile CFRP i części niestandardowe", "Rury, płyty, pręty i części CNC."], ["System wzmocnienia konstrukcyjnego", "Tkanina UD, płyta CFRP i żywica epoksydowa."]],
  tr: [["Karbon fiber takviyeler", "Kompozit üretimi için kuru kumaşlar ve tekstil takviyeleri."], ["Karbon fiber iplik, tow ve prekürsörler", "İleri işleme için iplik, tow, roving ve PAN."], ["Karbon fiber prepregler", "Kontrollü kalıplama için reçine emdirilmiş malzemeler."], ["Kırpılmış ve öğütülmüş karbon fiber", "Plastik ve reçine için kısa elyaf ve toz."], ["CFRP profiller ve özel parçalar", "Tüp, plaka, çubuk ve CNC parçalar."], ["Yapısal güçlendirme sistemi", "UD kumaş, CFRP plaka ve epoksi reçine."]],
  uk: [["Вуглецеві армувальні матеріали", "Сухі тканини та текстильне армування для композитів."], ["Вуглецева пряжа, tow і прекурсори", "Пряжа, tow, roving і PAN для подальшої переробки."], ["Вуглецеві препреги", "Матеріали, просочені смолою, для контрольованого формування."], ["Рубане та мелене вуглецеве волокно", "Коротке волокно і порошок для пластиків та смол."], ["Профілі CFRP і спеціальні деталі", "Труби, листи, стрижні та деталі CNC."], ["Система конструкційного підсилення", "Тканина UD, пластина CFRP та епоксидна смола."]],
  vi: [["Vật liệu gia cường sợi carbon", "Vải khô và vật liệu gia cường dệt cho composite."], ["Sợi, tow và vật liệu tiền chất carbon", "Sợi, tow, roving và PAN cho gia công tiếp theo."], ["Prepreg carbon", "Vật liệu tẩm nhựa cho quá trình tạo hình có kiểm soát."], ["Sợi carbon cắt và nghiền", "Sợi ngắn và bột cho nhựa và resin."], ["Profile CFRP và chi tiết theo yêu cầu", "Ống, tấm, thanh và chi tiết CNC."], ["Hệ gia cường kết cấu", "Vải UD, tấm CFRP và nhựa epoxy."]],
  th: [["วัสดุเสริมแรงคาร์บอนไฟเบอร์", "ผ้าแห้งและวัสดุเสริมแรงสิ่งทอสำหรับคอมโพสิต"], ["เส้นใย tow และวัสดุต้นกำเนิดคาร์บอน", "เส้นใย tow roving และ PAN สำหรับการแปรรูปต่อ"], ["prepreg คาร์บอน", "วัสดุชุบเรซินสำหรับการขึ้นรูปที่ควบคุมได้"], ["คาร์บอนไฟเบอร์ตัดและบด", "เส้นใยสั้นและผงสำหรับพลาสติกและเรซิน"], ["โปรไฟล์ CFRP และชิ้นส่วนสั่งทำ", "ท่อ แผ่น แท่ง และชิ้นส่วน CNC"], ["ระบบเสริมกำลังโครงสร้าง", "ผ้า UD แผ่น CFRP และเรซินอีพ็อกซี"]],
};

const familyKeys = ["Carbon Fiber Reinforcements", "Carbon Fiber Yarn, Tow & Precursor Materials", "Prepreg Carbon Fiber Materials", "Chopped & Milled Carbon Fiber", "CFRP Profiles & Custom Parts", "Structural Strengthening System"] as const;
export const extendedFamilyTranslations = Object.fromEntries(
  Object.entries(familyValues).map(([locale, values]) => [locale, Object.fromEntries(familyKeys.map((key, index) => [key, { title: values[index][0], description: values[index][1] }]))]),
) as Record<ExtendedLocale, Record<string, { title: string; description: string }>>;

const fieldFallback: Record<ExtendedLocale, string> = { ru: "Укажите требование", ar: "حدد المتطلبات", fr: "Précisez le besoin", ko: "요구 사항을 입력하십시오", pl: "Podaj wymaganie", tr: "Gereksinimi belirtin", uk: "Вкажіть вимогу", vi: "Nêu yêu cầu", th: "ระบุความต้องการ" };

export function translateExtendedPlaceholder(locale: ExtendedLocale, placeholder?: string) {
  if (!placeholder) return placeholder;
  const technicalOnly = /^[\d\sKxX+./,%°µ()\-]+(?:mm|cm|m|kg|g\/m2|mesh|C)?$/i.test(placeholder.trim());
  return technicalOnly ? placeholder : fieldFallback[locale];
}

export function translateExtendedRfqType(locale: ExtendedLocale, label: string) {
  const aliases: Record<string, string> = {
    "Carbon Fiber Yarn / Tow": "Carbon Fiber Yarn & Tow",
    "Woven Carbon Fiber Fabric": "Woven Carbon Fiber Fabric",
    "UD Carbon Fiber Fabric": "UD Carbon Fiber Fabric",
    "Spread Tow Carbon Fiber Fabric": "Spread Tow Carbon Fiber Fabric",
    "Prepreg Carbon Fiber Materials": "Prepreg Carbon Fiber Materials",
    "Chopped / Milled / Powder": "Milled Carbon Fiber Powder",
    "Structural Strengthening System": "Structural Strengthening System",
  };
  const extras: Record<ExtendedLocale, Record<string, string>> = {
    ru: { "Aramid / Carbon-Aramid Hybrid Fabric": "Арамидная / углеродно-арамидная гибридная ткань", "CFRP Profiles & Custom Parts": "Профили CFRP и детали на заказ", "Carbon Fiber Multiaxial NCF": "Мультиаксиальная углеродная ткань NCF" },
    ar: { "Aramid / Carbon-Aramid Hybrid Fabric": "نسيج أراميد / هجين كربون-أراميد", "CFRP Profiles & Custom Parts": "مقاطع CFRP وقطع مخصصة", "Carbon Fiber Multiaxial NCF": "نسيج كربون متعدد المحاور NCF" },
    fr: { "Aramid / Carbon-Aramid Hybrid Fabric": "Tissu aramide / hybride carbone-aramide", "CFRP Profiles & Custom Parts": "Profils CFRP et pièces sur mesure", "Carbon Fiber Multiaxial NCF": "Tissu carbone multiaxial NCF" },
    ko: { "Aramid / Carbon-Aramid Hybrid Fabric": "아라미드 / 탄소-아라미드 하이브리드 원단", "CFRP Profiles & Custom Parts": "CFRP 프로파일 및 맞춤 부품", "Carbon Fiber Multiaxial NCF": "다축 탄소섬유 NCF" },
    pl: { "Aramid / Carbon-Aramid Hybrid Fabric": "Tkanina aramidowa / hybrydowa węgiel-aramid", "CFRP Profiles & Custom Parts": "Profile CFRP i części niestandardowe", "Carbon Fiber Multiaxial NCF": "Multiaxialna tkanina węglowa NCF" },
    tr: { "Aramid / Carbon-Aramid Hybrid Fabric": "Aramid / karbon-aramid hibrit kumaş", "CFRP Profiles & Custom Parts": "CFRP profiller ve özel parçalar", "Carbon Fiber Multiaxial NCF": "Çok eksenli karbon fiber NCF" },
    uk: { "Aramid / Carbon-Aramid Hybrid Fabric": "Арамідна / вуглецево-арамідна гібридна тканина", "CFRP Profiles & Custom Parts": "Профілі CFRP і спеціальні деталі", "Carbon Fiber Multiaxial NCF": "Мультиаксіальна вуглецева тканина NCF" },
    vi: { "Aramid / Carbon-Aramid Hybrid Fabric": "Vải aramid / hybrid carbon-aramid", "CFRP Profiles & Custom Parts": "Profile CFRP và chi tiết theo yêu cầu", "Carbon Fiber Multiaxial NCF": "Vải carbon đa trục NCF" },
    th: { "Aramid / Carbon-Aramid Hybrid Fabric": "ผ้าอะรามิด / ไฮบริดคาร์บอน-อะรามิด", "CFRP Profiles & Custom Parts": "โปรไฟล์ CFRP และชิ้นส่วนสั่งทำ", "Carbon Fiber Multiaxial NCF": "ผ้าคาร์บอนไฟเบอร์หลายแกน NCF" },
  };
  return extras[locale][label] ?? extendedProductTranslations[locale][aliases[label] ?? label] ?? label;
}

const genericFieldTranslations: Record<ExtendedLocale, Record<string, string>> = {
  ru: { Grade: "Марка", Width: "Ширина", Packaging: "Упаковка", Dimensions: "Размеры", Tolerance: "Допуск", "Tow size": "Размер жгута (tow)", "Areal weight": "Поверхностная плотность", "Roll length": "Длина рулона", "Fiber grade": "Марка волокна", "Fiber length": "Длина волокна", "Powder size / mesh": "Размер порошка / mesh", "Target application": "Целевое применение", "Required performance": "Требуемые свойства", "Product type": "Тип продукта", "Surface finish": "Отделка поверхности", "Project type": "Тип проекта", "Material required": "Требуемый материал" },
  ar: { Grade: "الدرجة", Width: "العرض", Packaging: "التعبئة", Dimensions: "الأبعاد", Tolerance: "التسامح", "Tow size": "حجم tow", "Areal weight": "الوزن السطحي", "Roll length": "طول اللفة", "Fiber grade": "درجة الألياف", "Fiber length": "طول الألياف", "Powder size / mesh": "حجم المسحوق / mesh", "Target application": "التطبيق المستهدف", "Required performance": "الأداء المطلوب", "Product type": "نوع المنتج", "Surface finish": "تشطيب السطح", "Project type": "نوع المشروع", "Material required": "المادة المطلوبة" },
  fr: { Grade: "Grade", Width: "Largeur", Packaging: "Emballage", Dimensions: "Dimensions", Tolerance: "Tolérance", "Tow size": "Taille de tow", "Areal weight": "Masse surfacique", "Roll length": "Longueur du rouleau", "Fiber grade": "Grade de fibre", "Fiber length": "Longueur de fibre", "Powder size / mesh": "Taille de poudre / mesh", "Target application": "Application cible", "Required performance": "Performance requise", "Product type": "Type de produit", "Surface finish": "Finition de surface", "Project type": "Type de projet", "Material required": "Matériau requis" },
  ko: { Grade: "등급", Width: "폭", Packaging: "포장", Dimensions: "치수", Tolerance: "공차", "Tow size": "Tow 크기", "Areal weight": "면적 중량", "Roll length": "롤 길이", "Fiber grade": "섬유 등급", "Fiber length": "섬유 길이", "Powder size / mesh": "분말 크기 / mesh", "Target application": "목표 적용 분야", "Required performance": "요구 성능", "Product type": "제품 유형", "Surface finish": "표면 마감", "Project type": "프로젝트 유형", "Material required": "필요 소재" },
  pl: { Grade: "Klasa", Width: "Szerokość", Packaging: "Opakowanie", Dimensions: "Wymiary", Tolerance: "Tolerancja", "Tow size": "Rozmiar tow", "Areal weight": "Gramatura", "Roll length": "Długość rolki", "Fiber grade": "Klasa włókna", "Fiber length": "Długość włókna", "Powder size / mesh": "Rozmiar proszku / mesh", "Target application": "Docelowe zastosowanie", "Required performance": "Wymagane parametry", "Product type": "Typ produktu", "Surface finish": "Wykończenie powierzchni", "Project type": "Typ projektu", "Material required": "Wymagany materiał" },
  tr: { Grade: "Sınıf", Width: "Genişlik", Packaging: "Ambalaj", Dimensions: "Ölçüler", Tolerance: "Tolerans", "Tow size": "Tow boyutu", "Areal weight": "Birim alan ağırlığı", "Roll length": "Rulo uzunluğu", "Fiber grade": "Elyaf sınıfı", "Fiber length": "Elyaf uzunluğu", "Powder size / mesh": "Toz boyutu / mesh", "Target application": "Hedef uygulama", "Required performance": "Gerekli performans", "Product type": "Ürün tipi", "Surface finish": "Yüzey kalitesi", "Project type": "Proje tipi", "Material required": "Gerekli malzeme" },
  uk: { Grade: "Марка", Width: "Ширина", Packaging: "Пакування", Dimensions: "Розміри", Tolerance: "Допуск", "Tow size": "Розмір tow", "Areal weight": "Поверхнева щільність", "Roll length": "Довжина рулону", "Fiber grade": "Марка волокна", "Fiber length": "Довжина волокна", "Powder size / mesh": "Розмір порошку / mesh", "Target application": "Цільове застосування", "Required performance": "Необхідні властивості", "Product type": "Тип продукту", "Surface finish": "Оздоблення поверхні", "Project type": "Тип проєкту", "Material required": "Потрібний матеріал" },
  vi: { Grade: "Cấp sợi", Width: "Khổ rộng", Packaging: "Đóng gói", Dimensions: "Kích thước", Tolerance: "Dung sai", "Tow size": "Cỡ tow", "Areal weight": "Khối lượng trên diện tích", "Roll length": "Chiều dài cuộn", "Fiber grade": "Cấp sợi", "Fiber length": "Chiều dài sợi", "Powder size / mesh": "Cỡ bột / mesh", "Target application": "Ứng dụng mục tiêu", "Required performance": "Hiệu năng yêu cầu", "Product type": "Loại sản phẩm", "Surface finish": "Hoàn thiện bề mặt", "Project type": "Loại dự án", "Material required": "Vật liệu cần dùng" },
  th: { Grade: "เกรด", Width: "ความกว้าง", Packaging: "บรรจุภัณฑ์", Dimensions: "ขนาด", Tolerance: "ค่าความคลาดเคลื่อน", "Tow size": "ขนาด tow", "Areal weight": "น้ำหนักต่อพื้นที่", "Roll length": "ความยาวม้วน", "Fiber grade": "เกรดเส้นใย", "Fiber length": "ความยาวเส้นใย", "Powder size / mesh": "ขนาดผง / mesh", "Target application": "การใช้งานเป้าหมาย", "Required performance": "สมรรถนะที่ต้องการ", "Product type": "ประเภทผลิตภัณฑ์", "Surface finish": "ผิวสำเร็จ", "Project type": "ประเภทโครงการ", "Material required": "วัสดุที่ต้องการ" },
};

const additionalFieldTranslations: Record<ExtendedLocale, Record<string, string>> = {
  ru: { "Brand requirement": "Требование к бренду", "Sizing type": "Тип аппрета", "Compatible process": "Совместимый процесс", "Bobbin weight": "Вес бобины", "Weave type": "Тип переплетения", "Pattern size": "Размер рисунка", "Fiber type": "Тип волокна", "Fabric construction": "Структура ткани", "Color or pattern": "Цвет или рисунок", "Resin compatibility": "Совместимость со смолой", "Fiber direction requirement": "Требуемое направление волокон", "Resin system or process": "Система смолы или процесс", "Weave pattern": "Рисунок переплетения", "Surface appearance requirement": "Требование к внешнему виду", "Reinforcement type": "Тип армирования", "Fabric type": "Тип ткани", "Resin system": "Система смолы", "Resin content": "Содержание смолы", "Curing temperature": "Температура отверждения", "Processing method": "Метод переработки", "Storage requirement": "Условия хранения", "Shelf-life requirement": "Требуемый срок хранения", "Compatible resin or plastic": "Совместимая смола или пластик", "Manufacturing process": "Процесс производства", "UD fabric weight": "Плотность ткани UD", "CFRP plate width and thickness": "Ширина и толщина пластины CFRP", "Epoxy resin requirement": "Требование к эпоксидной смоле", "Project area": "Площадь проекта" },
  ar: { "Brand requirement": "متطلبات العلامة", "Sizing type": "نوع الطلاء السطحي", "Compatible process": "العملية المتوافقة", "Bobbin weight": "وزن البكرة", "Weave type": "نوع النسج", "Pattern size": "حجم النمط", "Fiber type": "نوع الألياف", "Fabric construction": "تركيب النسيج", "Color or pattern": "اللون أو النمط", "Resin compatibility": "توافق الراتنج", "Fiber direction requirement": "اتجاه الألياف المطلوب", "Resin system or process": "نظام الراتنج أو العملية", "Weave pattern": "نمط النسج", "Surface appearance requirement": "متطلبات مظهر السطح", "Reinforcement type": "نوع التقوية", "Fabric type": "نوع النسيج", "Resin system": "نظام الراتنج", "Resin content": "محتوى الراتنج", "Curing temperature": "درجة حرارة المعالجة", "Processing method": "طريقة التصنيع", "Storage requirement": "متطلبات التخزين", "Shelf-life requirement": "متطلبات مدة الصلاحية", "Compatible resin or plastic": "الراتنج أو البلاستيك المتوافق", "Manufacturing process": "عملية التصنيع", "UD fabric weight": "وزن نسيج UD", "CFRP plate width and thickness": "عرض وسماكة صفيحة CFRP", "Epoxy resin requirement": "متطلبات راتنج الإيبوكسي", "Project area": "مساحة المشروع" },
  fr: { "Brand requirement": "Exigence de marque", "Sizing type": "Type d'ensimage", "Compatible process": "Procédé compatible", "Bobbin weight": "Poids de bobine", "Weave type": "Type de tissage", "Pattern size": "Taille du motif", "Fiber type": "Type de fibre", "Fabric construction": "Construction du tissu", "Color or pattern": "Couleur ou motif", "Resin compatibility": "Compatibilité résine", "Fiber direction requirement": "Direction de fibre requise", "Resin system or process": "Système de résine ou procédé", "Weave pattern": "Motif de tissage", "Surface appearance requirement": "Aspect de surface recherché", "Reinforcement type": "Type de renfort", "Fabric type": "Type de tissu", "Resin system": "Système de résine", "Resin content": "Teneur en résine", "Curing temperature": "Température de cuisson", "Processing method": "Méthode de mise en œuvre", "Storage requirement": "Condition de stockage", "Shelf-life requirement": "Durée de conservation requise", "Compatible resin or plastic": "Résine ou plastique compatible", "Manufacturing process": "Procédé de fabrication", "UD fabric weight": "Masse du tissu UD", "CFRP plate width and thickness": "Largeur et épaisseur de la plaque CFRP", "Epoxy resin requirement": "Exigence de résine époxy", "Project area": "Surface du projet" },
  ko: { "Brand requirement": "브랜드 요구 사항", "Sizing type": "사이징 유형", "Compatible process": "호환 공정", "Bobbin weight": "보빈 중량", "Weave type": "직조 유형", "Pattern size": "패턴 크기", "Fiber type": "섬유 유형", "Fabric construction": "원단 구조", "Color or pattern": "색상 또는 패턴", "Resin compatibility": "수지 호환성", "Fiber direction requirement": "필요 섬유 방향", "Resin system or process": "수지 시스템 또는 공정", "Weave pattern": "직조 패턴", "Surface appearance requirement": "표면 외관 요구 사항", "Reinforcement type": "보강재 유형", "Fabric type": "원단 유형", "Resin system": "수지 시스템", "Resin content": "수지 함량", "Curing temperature": "경화 온도", "Processing method": "가공 방법", "Storage requirement": "보관 요구 사항", "Shelf-life requirement": "유효 기간 요구 사항", "Compatible resin or plastic": "호환 수지 또는 플라스틱", "Manufacturing process": "제조 공정", "UD fabric weight": "UD 원단 중량", "CFRP plate width and thickness": "CFRP 판 폭 및 두께", "Epoxy resin requirement": "에폭시 수지 요구 사항", "Project area": "프로젝트 면적" },
  pl: { "Brand requirement": "Wymagania dotyczące marki", "Sizing type": "Rodzaj preparacji", "Compatible process": "Zgodny proces", "Bobbin weight": "Masa szpuli", "Weave type": "Rodzaj splotu", "Pattern size": "Rozmiar wzoru", "Fiber type": "Rodzaj włókna", "Fabric construction": "Konstrukcja tkaniny", "Color or pattern": "Kolor lub wzór", "Resin compatibility": "Zgodność z żywicą", "Fiber direction requirement": "Wymagany kierunek włókien", "Resin system or process": "System żywiczny lub proces", "Weave pattern": "Wzór splotu", "Surface appearance requirement": "Wymagany wygląd powierzchni", "Reinforcement type": "Rodzaj zbrojenia", "Fabric type": "Rodzaj tkaniny", "Resin system": "System żywiczny", "Resin content": "Zawartość żywicy", "Curing temperature": "Temperatura utwardzania", "Processing method": "Metoda przetwarzania", "Storage requirement": "Wymagania przechowywania", "Shelf-life requirement": "Wymagany okres trwałości", "Compatible resin or plastic": "Zgodna żywica lub tworzywo", "Manufacturing process": "Proces produkcyjny", "UD fabric weight": "Gramatura tkaniny UD", "CFRP plate width and thickness": "Szerokość i grubość płyty CFRP", "Epoxy resin requirement": "Wymagania dotyczące żywicy epoksydowej", "Project area": "Powierzchnia projektu" },
  tr: { "Brand requirement": "Marka gereksinimi", "Sizing type": "Sizing türü", "Compatible process": "Uyumlu proses", "Bobbin weight": "Bobin ağırlığı", "Weave type": "Dokuma türü", "Pattern size": "Desen boyutu", "Fiber type": "Elyaf türü", "Fabric construction": "Kumaş yapısı", "Color or pattern": "Renk veya desen", "Resin compatibility": "Reçine uyumluluğu", "Fiber direction requirement": "Gerekli elyaf yönü", "Resin system or process": "Reçine sistemi veya proses", "Weave pattern": "Dokuma deseni", "Surface appearance requirement": "Yüzey görünümü gereksinimi", "Reinforcement type": "Takviye türü", "Fabric type": "Kumaş türü", "Resin system": "Reçine sistemi", "Resin content": "Reçine oranı", "Curing temperature": "Kürleme sıcaklığı", "Processing method": "İşleme yöntemi", "Storage requirement": "Depolama gereksinimi", "Shelf-life requirement": "Raf ömrü gereksinimi", "Compatible resin or plastic": "Uyumlu reçine veya plastik", "Manufacturing process": "Üretim prosesi", "UD fabric weight": "UD kumaş ağırlığı", "CFRP plate width and thickness": "CFRP plaka genişliği ve kalınlığı", "Epoxy resin requirement": "Epoksi reçine gereksinimi", "Project area": "Proje alanı" },
  uk: { "Brand requirement": "Вимоги до бренду", "Sizing type": "Тип апрету", "Compatible process": "Сумісний процес", "Bobbin weight": "Маса бобіни", "Weave type": "Тип переплетення", "Pattern size": "Розмір візерунка", "Fiber type": "Тип волокна", "Fabric construction": "Будова тканини", "Color or pattern": "Колір або візерунок", "Resin compatibility": "Сумісність зі смолою", "Fiber direction requirement": "Потрібний напрямок волокон", "Resin system or process": "Система смоли або процес", "Weave pattern": "Візерунок переплетення", "Surface appearance requirement": "Вимоги до поверхні", "Reinforcement type": "Тип армування", "Fabric type": "Тип тканини", "Resin system": "Система смоли", "Resin content": "Вміст смоли", "Curing temperature": "Температура затвердіння", "Processing method": "Метод обробки", "Storage requirement": "Умови зберігання", "Shelf-life requirement": "Строк зберігання", "Compatible resin or plastic": "Сумісна смола або пластик", "Manufacturing process": "Виробничий процес", "UD fabric weight": "Щільність тканини UD", "CFRP plate width and thickness": "Ширина та товщина пластини CFRP", "Epoxy resin requirement": "Вимоги до епоксидної смоли", "Project area": "Площа проєкту" },
  vi: { "Brand requirement": "Yêu cầu thương hiệu", "Sizing type": "Loại sizing", "Compatible process": "Quy trình phù hợp", "Bobbin weight": "Khối lượng bobbin", "Weave type": "Kiểu dệt", "Pattern size": "Kích thước hoa văn", "Fiber type": "Loại sợi", "Fabric construction": "Cấu trúc vải", "Color or pattern": "Màu sắc hoặc hoa văn", "Resin compatibility": "Tương thích nhựa", "Fiber direction requirement": "Yêu cầu hướng sợi", "Resin system or process": "Hệ nhựa hoặc quy trình", "Weave pattern": "Mẫu dệt", "Surface appearance requirement": "Yêu cầu bề mặt", "Reinforcement type": "Loại gia cường", "Fabric type": "Loại vải", "Resin system": "Hệ nhựa", "Resin content": "Hàm lượng nhựa", "Curing temperature": "Nhiệt độ đóng rắn", "Processing method": "Phương pháp gia công", "Storage requirement": "Yêu cầu bảo quản", "Shelf-life requirement": "Thời hạn lưu kho", "Compatible resin or plastic": "Nhựa hoặc plastic tương thích", "Manufacturing process": "Quy trình sản xuất", "UD fabric weight": "Khối lượng vải UD", "CFRP plate width and thickness": "Chiều rộng và độ dày tấm CFRP", "Epoxy resin requirement": "Yêu cầu nhựa epoxy", "Project area": "Diện tích dự án" },
  th: { "Brand requirement": "ข้อกำหนดแบรนด์", "Sizing type": "ชนิด sizing", "Compatible process": "กระบวนการที่เข้ากันได้", "Bobbin weight": "น้ำหนักบ๊อบบิน", "Weave type": "ชนิดการทอ", "Pattern size": "ขนาดลาย", "Fiber type": "ชนิดเส้นใย", "Fabric construction": "โครงสร้างผ้า", "Color or pattern": "สีหรือลาย", "Resin compatibility": "ความเข้ากันได้กับเรซิน", "Fiber direction requirement": "ทิศทางเส้นใยที่ต้องการ", "Resin system or process": "ระบบเรซินหรือกระบวนการ", "Weave pattern": "ลายทอ", "Surface appearance requirement": "ข้อกำหนดลักษณะผิว", "Reinforcement type": "ประเภทวัสดุเสริมแรง", "Fabric type": "ประเภทผ้า", "Resin system": "ระบบเรซิน", "Resin content": "ปริมาณเรซิน", "Curing temperature": "อุณหภูมิการบ่ม", "Processing method": "วิธีการแปรรูป", "Storage requirement": "ข้อกำหนดการจัดเก็บ", "Shelf-life requirement": "อายุการเก็บ", "Compatible resin or plastic": "เรซินหรือพลาสติกที่เข้ากันได้", "Manufacturing process": "กระบวนการผลิต", "UD fabric weight": "น้ำหนักผ้า UD", "CFRP plate width and thickness": "ความกว้างและความหนาแผ่น CFRP", "Epoxy resin requirement": "ข้อกำหนดเรซินอีพ็อกซี", "Project area": "พื้นที่โครงการ" },
};

export function translateExtendedField(locale: ExtendedLocale, label: string) {
  const dualCoreFields: Record<ExtendedLocale, Record<string, string>> = {
    ru: { "NCF architecture": "Архитектура NCF", "Fiber directions": "Направления волокон", "Stitch requirement": "Требование к прошивке", "Resin process": "Процесс со смолой" },
    ar: { "NCF architecture": "بنية NCF", "Fiber directions": "اتجاهات الألياف", "Stitch requirement": "متطلبات خيط التثبيت", "Resin process": "عملية الراتنج" },
    fr: { "NCF architecture": "Architecture NCF", "Fiber directions": "Orientations des fibres", "Stitch requirement": "Exigence de couture", "Resin process": "Procédé résine" },
    ko: { "NCF architecture": "NCF 구조", "Fiber directions": "섬유 방향", "Stitch requirement": "스티치 요구 사항", "Resin process": "수지 공정" },
    pl: { "NCF architecture": "Architektura NCF", "Fiber directions": "Kierunki włókien", "Stitch requirement": "Wymagania dotyczące szwu", "Resin process": "Proces żywiczny" },
    tr: { "NCF architecture": "NCF mimarisi", "Fiber directions": "Elyaf yönleri", "Stitch requirement": "Dikiş gereksinimi", "Resin process": "Reçine prosesi" },
    uk: { "NCF architecture": "Архітектура NCF", "Fiber directions": "Напрямки волокон", "Stitch requirement": "Вимоги до прошивання", "Resin process": "Процес зі смолою" },
    vi: { "NCF architecture": "Cấu trúc NCF", "Fiber directions": "Hướng sợi", "Stitch requirement": "Yêu cầu chỉ khâu", "Resin process": "Quy trình nhựa" },
    th: { "NCF architecture": "โครงสร้าง NCF", "Fiber directions": "ทิศทางเส้นใย", "Stitch requirement": "ข้อกำหนดการเย็บยึด", "Resin process": "กระบวนการเรซิน" },
  };
  return dualCoreFields[locale][label] ?? additionalFieldTranslations[locale][label] ?? genericFieldTranslations[locale][label] ?? fieldFallback[locale];
}
