import type { LocalizedLocale } from "@/lib/i18n/config";

export type FiberOpticCableDrumLocalizedContent = {
  name: string;
  shortName: string;
  category: string;
  description: string;
  heroCopy: string;
  seo: { title: string; description: string; keywords: string[] };
  intro: string[];
  applications: string[];
  faqs: { question: string; answer: string }[];
};

export const fiberOpticCableDrumLocalizedContent: Record<LocalizedLocale, FiberOpticCableDrumLocalizedContent> = {
  es: {
    name: "Carrete de cable de fibra óptica con desenrollado interno", shortName: "Carrete de fibra óptica", category: "Manejo industrial de cable de fibra óptica",
    description: "Carretes de cable de fibra óptica con desenrollado interno para proyectos cualificados de despliegue de cable civil e industrial, con series de 1 km a 60 km según los manuales suministrados.",
    heroCopy: "Elija la longitud requerida, la serie de carrete, la interfaz de integración, la cantidad, el destino y la aplicación civil o industrial final. Todo se revisa antes de la cotización.",
    seo: { title: "Carrete de cable de fibra óptica | Desenrollado interno", description: "Carretes de cable de fibra óptica con desenrollado interno para integración civil e industrial cualificada, con referencias G.657.A2 y opciones de 1-60 km.", keywords: ["carrete de cable de fibra óptica", "carrete de desenrollado interno", "bobina de fibra óptica"] },
    intro: ["El carrete conserva una longitud seleccionada de fibra óptica dentro de una carcasa protegida y permite el desenrollado desde el interior.", "Los manuales suministrados describen las series ZY-SI de 1-15 km, ZY-MI de 20-40 km y ZY-LI de 50-60 km. La referencia publicada es fibra G.657.A2 de 0.25 mm.", "Las dimensiones, el embalaje, la masa, la configuración de terminales y los documentos actuales se confirman para cada pedido. El uso final, el usuario final y el destino pueden requerir revisión de cumplimiento."],
    applications: ["Instalaciones temporales de monitoreo e inspección industrial", "Pruebas controladas de despliegue de cable civil", "Proyectos de telecomunicaciones e integración de equipos", "Inspección de túneles, tuberías y espacios cerrados", "Proyectos civiles de infraestructura fija o móvil cualificados"],
    faqs: [{ question: "¿Qué longitudes están disponibles?", answer: "Los manuales indican series de 1-15 km, 20-40 km y 50-60 km. Indique la longitud requerida para revisar el modelo y la documentación actuales." }, { question: "¿El embalaje y la masa son valores fijos?", answer: "No. Los manuales suministrados contienen referencias no uniformes. La masa, el cartón y el embalaje de exportación se confirman en la cotización." }, { question: "¿Qué datos se necesitan para cotizar?", answer: "Indique la serie o longitud, la interfaz requerida, la cantidad, el destino, los documentos requeridos y la aplicación civil o industrial final." }],
  },
  "pt-br": {
    name: "Tambor de cabo de fibra óptica com desenrolamento interno", shortName: "Tambor de fibra óptica", category: "Manuseio industrial de cabo de fibra óptica",
    description: "Tambores de cabo de fibra óptica com desenrolamento interno para projetos qualificados de implantação de cabos civis e industriais, com séries de 1 km a 60 km conforme os manuais fornecidos.",
    heroCopy: "Informe o comprimento necessário, a série do tambor, a interface de integração, a quantidade, o destino e a aplicação civil ou industrial final. Esses dados são analisados antes da cotação.",
    seo: { title: "Tambor de cabo de fibra óptica | Desenrolamento interno", description: "Tambores de cabo de fibra óptica com desenrolamento interno para integração civil e industrial qualificada, com referência G.657.A2 e opções de 1-60 km.", keywords: ["tambor de cabo de fibra óptica", "tambor de desenrolamento interno", "bobina de fibra óptica"] },
    intro: ["O tambor mantém um comprimento selecionado de fibra óptica em uma carcaça protegida e permite o desenrolamento a partir do interior.", "Os manuais fornecidos descrevem ZY-SI para 1-15 km, ZY-MI para 20-40 km e ZY-LI para 50-60 km. A referência publicada é fibra G.657.A2 de 0.25 mm.", "Dimensões, embalagem, massa, configuração de terminais e documentos atuais são confirmados para cada pedido. Uso final, usuário final e destino podem exigir revisão de conformidade."],
    applications: ["Instalações temporárias de monitoramento e inspeção industrial", "Testes controlados de implantação de cabo civil", "Projetos de telecomunicações e integração de equipamentos", "Inspeção de túneis, tubulações e espaços fechados", "Projetos qualificados de infraestrutura civil fixa ou móvel"],
    faqs: [{ question: "Quais comprimentos estão disponíveis?", answer: "Os manuais indicam séries de 1-15 km, 20-40 km e 50-60 km. Informe o comprimento desejado para revisar o modelo e a documentação atuais." }, { question: "A embalagem e a massa são valores fixos?", answer: "Não. Os manuais fornecidos apresentam referências não uniformes. A massa, a caixa e a embalagem de exportação são confirmadas na cotação." }, { question: "Quais dados são necessários para cotação?", answer: "Informe a série ou o comprimento, a interface necessária, a quantidade, o destino, os documentos requeridos e a aplicação civil ou industrial final." }],
  },
  ru: {
    name: "Катушка оптоволоконного кабеля с внутренней размоткой", shortName: "Оптоволоконная катушка", category: "Промышленная работа с оптоволоконным кабелем",
    description: "Катушки оптоволоконного кабеля с внутренней размоткой для квалифицированных гражданских и промышленных проектов прокладки кабеля; по предоставленным руководствам доступны серии от 1 до 60 км.",
    heroCopy: "Укажите требуемую длину, серию катушки, интерфейс интеграции, количество, страну назначения и конечное гражданское или промышленное применение для проверки до предложения.",
    seo: { title: "Катушка оптоволоконного кабеля | Внутренняя размотка", description: "Катушки оптоволоконного кабеля с внутренней размоткой для квалифицированной гражданской и промышленной интеграции, с справочной оптикой G.657.A2 и сериями 1-60 км.", keywords: ["катушка оптоволоконного кабеля", "катушка внутренней размотки", "барабан оптоволокна"] },
    intro: ["Катушка хранит выбранную длину оптического волокна в защищенном корпусе и поддерживает внутреннюю размотку кабеля.", "В руководствах указаны ZY-SI для 1-15 км, ZY-MI для 20-40 км и ZY-LI для 50-60 км. Опубликованная справочная характеристика: волокно G.657.A2 диаметром 0.25 мм.", "Габариты, упаковка, масса, конфигурация терминала и текущие документы подтверждаются для заказа. Конечное применение, конечный пользователь и страна назначения могут требовать проверки соответствия."],
    applications: ["Временные промышленные системы мониторинга и инспекции", "Контролируемые гражданские испытания прокладки кабеля", "Телекоммуникационные проекты и интеграция оборудования", "Инспекция тоннелей, трубопроводов и замкнутых пространств", "Квалифицированные проекты стационарной или мобильной гражданской инфраструктуры"],
    faqs: [{ question: "Какие длины доступны?", answer: "Руководства указывают серии 1-15 км, 20-40 км и 50-60 км. Укажите требуемую длину для проверки модели и текущей документации." }, { question: "Упаковка и масса фиксированы?", answer: "Нет. В предоставленных версиях руководств есть неодинаковые сведения. Масса, картон и экспортная упаковка подтверждаются в предложении." }, { question: "Какие сведения нужны для предложения?", answer: "Укажите серию или длину, требуемый интерфейс, количество, страну назначения, необходимые документы и конечное гражданское или промышленное применение." }],
  },
  ar: {
    name: "بكرة كابل ألياف ضوئية بتغذية داخلية", shortName: "بكرة ألياف ضوئية", category: "مناولة صناعية لكابل الألياف الضوئية",
    description: "بكرات كابل ألياف ضوئية بتغذية داخلية لمشروعات مدنية وصناعية مؤهلة لنشر الكابلات، بسلاسل من 1 كم إلى 60 كم وفقاً للأدلة المقدمة.",
    heroCopy: "يرجى تحديد الطول المطلوب وسلسلة البكرة وواجهة التكامل والكمية والوجهة والاستخدام المدني أو الصناعي النهائي. تتم مراجعة هذه البيانات قبل عرض السعر.",
    seo: { title: "بكرة كابل ألياف ضوئية | تغذية داخلية", description: "بكرات كابل ألياف ضوئية بتغذية داخلية لمشروعات التكامل المدني والصناعي المؤهلة، مع مرجع G.657.A2 وخيارات من 1 إلى 60 كم.", keywords: ["بكرة كابل ألياف ضوئية", "بكرة تغذية داخلية", "بكرة ألياف ضوئية"] },
    intro: ["تحفظ البكرة طولاً محدداً من الألياف الضوئية داخل غلاف محمي وتسمح بخروج الكابل من الداخل.", "تصف الأدلة المقدمة ZY-SI لمسافة 1-15 كم وZY-MI لمسافة 20-40 كم وZY-LI لمسافة 50-60 كم. المرجع المنشور هو ألياف G.657.A2 بقطر 0.25 مم.", "يتم تأكيد الأبعاد والتعبئة والكتلة وتكوين الطرف والمستندات الحالية لكل طلب. قد يتطلب الاستخدام النهائي والمستخدم النهائي والوجهة مراجعة امتثال."],
    applications: ["تركيبات مراقبة وفحص صناعية مؤقتة", "تجارب مدنية مضبوطة لنشر الكابلات", "مشروعات الاتصالات وتكامل المعدات", "فحص الأنفاق وخطوط الأنابيب والأماكن المغلقة", "مشروعات بنية تحتية مدنية ثابتة أو متنقلة مؤهلة"],
    faqs: [{ question: "ما الأطوال المتاحة؟", answer: "تشير الأدلة إلى سلاسل 1-15 كم و20-40 كم و50-60 كم. حدد الطول المطلوب لمراجعة الطراز والمستندات الحالية." }, { question: "هل التعبئة والكتلة قيم ثابتة؟", answer: "لا. تحتوي نسخ الأدلة المقدمة على مراجع غير متطابقة. يتم تأكيد الكتلة والكرتون وتعبئة التصدير في عرض السعر." }, { question: "ما المعلومات المطلوبة لعرض السعر؟", answer: "حدد السلسلة أو الطول وواجهة التكامل والكمية والوجهة والمستندات المطلوبة والاستخدام المدني أو الصناعي النهائي." }],
  },
  fr: {
    name: "Touret de câble à fibre optique à déroulement interne", shortName: "Touret fibre optique", category: "Manutention industrielle de câble à fibre optique",
    description: "Tourets de câble à fibre optique à déroulement interne pour projets qualifiés de déploiement de câbles civils et industriels, avec des séries de 1 km à 60 km selon les manuels fournis.",
    heroCopy: "Indiquez la longueur requise, la série de touret, l'interface d'intégration, la quantité, la destination et l'application civile ou industrielle finale. Ces éléments sont examinés avant devis.",
    seo: { title: "Touret de câble à fibre optique | Déroulement interne", description: "Tourets de câble à fibre optique à déroulement interne pour une intégration civile et industrielle qualifiée, avec référence G.657.A2 et options de 1 à 60 km.", keywords: ["touret câble fibre optique", "touret déroulement interne", "bobine fibre optique"] },
    intro: ["Le touret conserve une longueur définie de fibre optique dans un boîtier protégé et permet un déroulement depuis l'intérieur.", "Les manuels fournis décrivent ZY-SI pour 1-15 km, ZY-MI pour 20-40 km et ZY-LI pour 50-60 km. La référence publiée est une fibre G.657.A2 de 0.25 mm.", "Dimensions, emballage, masse, configuration de terminal et documents en vigueur sont confirmés pour chaque commande. L'usage final, l'utilisateur final et la destination peuvent nécessiter un examen de conformité."],
    applications: ["Installations temporaires de surveillance et d'inspection industrielle", "Essais contrôlés de déploiement de câble civil", "Projets de télécommunications et d'intégration d'équipements", "Inspection de tunnels, conduites et espaces confinés", "Projets qualifiés d'infrastructure civile fixe ou mobile"],
    faqs: [{ question: "Quelles longueurs sont disponibles ?", answer: "Les manuels indiquent des séries de 1-15 km, 20-40 km et 50-60 km. Indiquez la longueur pour examiner le modèle et la documentation actuelle." }, { question: "L'emballage et la masse sont-ils fixes ?", answer: "Non. Les manuels fournis présentent des références non uniformes. La masse, le carton et l'emballage export sont confirmés dans le devis." }, { question: "Quelles informations sont nécessaires pour un devis ?", answer: "Indiquez la série ou la longueur, l'interface requise, la quantité, la destination, les documents requis et l'application civile ou industrielle finale." }],
  },
  ko: {
    name: "내부 인출형 광섬유 케이블 드럼", shortName: "광섬유 케이블 드럼", category: "산업용 광섬유 케이블 취급",
    description: "제공된 매뉴얼 기준 1 km~60 km 시리즈를 갖춘, 적격 민간 및 산업용 케이블 배치 프로젝트용 내부 인출형 광섬유 케이블 드럼입니다.",
    heroCopy: "필요 길이, 드럼 시리즈, 통합 인터페이스, 수량, 목적지 및 최종 민간 또는 산업용 적용 분야를 알려 주십시오. 견적 전에 검토합니다.",
    seo: { title: "광섬유 케이블 드럼 | 내부 인출 방식", description: "적격 민간 및 산업 통합 프로젝트용 내부 인출형 광섬유 케이블 드럼. G.657.A2 기준과 1-60 km 시리즈 옵션을 제공합니다.", keywords: ["광섬유 케이블 드럼", "내부 인출 드럼", "광섬유 릴"] },
    intro: ["드럼은 선택한 길이의 광섬유를 보호 하우징에 보관하고 내부에서 케이블을 인출하도록 설계되었습니다.", "제공된 매뉴얼은 ZY-SI 1-15 km, ZY-MI 20-40 km, ZY-LI 50-60 km를 설명합니다. 공개 기준은 G.657.A2, 직경 0.25 mm 광섬유입니다.", "치수, 포장, 질량, 단자 구성 및 최신 문서는 주문별로 확인합니다. 최종 용도, 최종 사용자 및 목적지는 규정 검토가 필요할 수 있습니다."],
    applications: ["임시 산업 모니터링 및 검사 설비", "통제된 민간 케이블 배치 시험", "통신 및 장비 통합 프로젝트", "터널, 파이프라인 및 밀폐 공간 검사", "적격 고정식 또는 이동식 민간 인프라 프로젝트"],
    faqs: [{ question: "어떤 길이를 선택할 수 있습니까?", answer: "매뉴얼에는 1-15 km, 20-40 km, 50-60 km 시리즈가 나와 있습니다. 모델과 최신 문서를 검토할 수 있도록 필요 길이를 알려 주십시오." }, { question: "포장과 질량은 고정값입니까?", answer: "아닙니다. 제공된 매뉴얼에는 일관되지 않은 참고 정보가 있습니다. 질량, 카톤 및 수출 포장은 견적에서 확인합니다." }, { question: "견적에 필요한 정보는 무엇입니까?", answer: "시리즈 또는 길이, 필요한 인터페이스, 수량, 목적지, 필요 문서 및 최종 민간 또는 산업용 적용 분야를 알려 주십시오." }],
  },
  pl: {
    name: "Bęben światłowodowy z odwijaniem wewnętrznym", shortName: "Bęben światłowodowy", category: "Przemysłowa obsługa kabli światłowodowych",
    description: "Bębny kabli światłowodowych z odwijaniem wewnętrznym do kwalifikowanych cywilnych i przemysłowych projektów układania kabli, z seriami 1 km-60 km zgodnie z dostarczonymi instrukcjami.",
    heroCopy: "Podaj wymaganą długość, serię bębna, interfejs integracyjny, ilość, kraj docelowy oraz końcowe zastosowanie cywilne lub przemysłowe. Dane są sprawdzane przed ofertą.",
    seo: { title: "Bęben światłowodowy | Odwijanie wewnętrzne", description: "Bębny światłowodowe z odwijaniem wewnętrznym do kwalifikowanej integracji cywilnej i przemysłowej, z odniesieniem G.657.A2 i opcjami 1-60 km.", keywords: ["bęben kabla światłowodowego", "bęben odwijania wewnętrznego", "szpula światłowodowa"] },
    intro: ["Bęben przechowuje wybraną długość włókna optycznego w chronionej obudowie i umożliwia odwijanie kabla od wewnątrz.", "Dostarczone instrukcje opisują ZY-SI dla 1-15 km, ZY-MI dla 20-40 km i ZY-LI dla 50-60 km. Opublikowane odniesienie to włókno G.657.A2 o średnicy 0.25 mm.", "Wymiary, opakowanie, masa, konfiguracja terminala i aktualne dokumenty są potwierdzane dla każdego zamówienia. Zastosowanie końcowe, użytkownik końcowy i kraj docelowy mogą wymagać weryfikacji zgodności."],
    applications: ["Tymczasowe instalacje monitoringu i inspekcji przemysłowej", "Kontrolowane cywilne próby układania kabla", "Projekty telekomunikacyjne i integracja urządzeń", "Inspekcja tuneli, rurociągów i przestrzeni zamkniętych", "Kwalifikowane projekty stałej lub mobilnej infrastruktury cywilnej"],
    faqs: [{ question: "Jakie długości są dostępne?", answer: "Instrukcje podają serie 1-15 km, 20-40 km i 50-60 km. Podaj potrzebną długość, aby sprawdzić model i aktualną dokumentację." }, { question: "Czy opakowanie i masa są stałe?", answer: "Nie. Dostarczone instrukcje zawierają niejednolite informacje. Masa, karton i opakowanie eksportowe są potwierdzane w ofercie." }, { question: "Jakie dane są potrzebne do wyceny?", answer: "Podaj serię lub długość, wymagany interfejs, ilość, kraj docelowy, potrzebne dokumenty oraz końcowe zastosowanie cywilne lub przemysłowe." }],
  },
  tr: {
    name: "İçten açılmalı fiber optik kablo tamburu", shortName: "Fiber optik kablo tamburu", category: "Endüstriyel fiber optik kablo kullanımı",
    description: "Sağlanan kılavuzlara göre 1 km-60 km serileri bulunan, nitelikli sivil ve endüstriyel kablo döşeme projeleri için içten açılmalı fiber optik kablo tamburları.",
    heroCopy: "Gerekli uzunluğu, tambur serisini, entegrasyon arayüzünü, miktarı, varış ülkesini ve nihai sivil veya endüstriyel uygulamayı belirtin. Tekliften önce incelenir.",
    seo: { title: "Fiber optik kablo tamburu | İçten açılma", description: "Nitelikli sivil ve endüstriyel entegrasyon projeleri için içten açılmalı fiber optik kablo tamburları; G.657.A2 referansı ve 1-60 km seçenekleri.", keywords: ["fiber optik kablo tamburu", "içten açılmalı tambur", "fiber optik makara"] },
    intro: ["Tambur, seçilmiş optik fiber uzunluğunu korumalı bir gövdede tutar ve kablonun içeriden açılmasını sağlar.", "Sağlanan kılavuzlar ZY-SI için 1-15 km, ZY-MI için 20-40 km ve ZY-LI için 50-60 km tanımlar. Yayınlanan referans G.657.A2, 0.25 mm fiberidir.", "Boyutlar, ambalaj, kütle, terminal yapılandırması ve güncel belgeler siparişe göre doğrulanır. Nihai kullanım, son kullanıcı ve varış ülkesi uygunluk incelemesi gerektirebilir."],
    applications: ["Geçici endüstriyel izleme ve inceleme kurulumları", "Kontrollü sivil kablo döşeme denemeleri", "Telekomünikasyon ve ekipman entegrasyon projeleri", "Tünel, boru hattı ve kapalı alan incelemeleri", "Nitelikli sabit veya mobil sivil altyapı projeleri"],
    faqs: [{ question: "Hangi uzunluklar mevcuttur?", answer: "Kılavuzlar 1-15 km, 20-40 km ve 50-60 km serilerini belirtir. Model ve güncel belgelerin incelenmesi için gerekli uzunluğu paylaşın." }, { question: "Ambalaj ve kütle sabit midir?", answer: "Hayır. Sağlanan kılavuzlarda tutarsız referanslar bulunmaktadır. Kütle, karton ve ihracat ambalajı teklifte doğrulanır." }, { question: "Teklif için hangi bilgiler gerekir?", answer: "Seri veya uzunluk, gerekli arayüz, miktar, varış ülkesi, gerekli belgeler ve nihai sivil veya endüstriyel uygulamayı paylaşın." }],
  },
  uk: {
    name: "Котушка волоконно-оптичного кабелю з внутрішньою розмоткою", shortName: "Волоконно-оптична котушка", category: "Промислова робота з волоконно-оптичним кабелем",
    description: "Котушки волоконно-оптичного кабелю з внутрішньою розмоткою для кваліфікованих цивільних і промислових проєктів прокладання кабелю; за наданими посібниками доступні серії від 1 км до 60 км.",
    heroCopy: "Вкажіть потрібну довжину, серію котушки, інтерфейс інтеграції, кількість, країну призначення та кінцеве цивільне або промислове застосування для перевірки перед пропозицією.",
    seo: { title: "Котушка волоконно-оптичного кабелю | Внутрішня розмотка", description: "Котушки волоконно-оптичного кабелю з внутрішньою розмоткою для кваліфікованої цивільної та промислової інтеграції, з посиланням на G.657.A2 і серіями 1-60 км.", keywords: ["котушка волоконно-оптичного кабелю", "котушка внутрішньої розмотки", "барабан оптоволокна"] },
    intro: ["Котушка зберігає вибрану довжину оптичного волокна в захищеному корпусі та підтримує внутрішню розмотку кабелю.", "Надані посібники описують ZY-SI для 1-15 км, ZY-MI для 20-40 км і ZY-LI для 50-60 км. Опубліковане довідкове значення: волокно G.657.A2 діаметром 0.25 мм.", "Габарити, пакування, маса, конфігурація терміналу й актуальні документи підтверджуються для замовлення. Кінцеве використання, кінцевий користувач і країна призначення можуть потребувати перевірки відповідності."],
    applications: ["Тимчасові промислові системи моніторингу та інспекції", "Контрольовані цивільні випробування прокладання кабелю", "Телекомунікаційні проєкти та інтеграція обладнання", "Інспекція тунелів, трубопроводів і замкнених просторів", "Кваліфіковані проєкти стаціонарної або мобільної цивільної інфраструктури"],
    faqs: [{ question: "Які довжини доступні?", answer: "Посібники вказують серії 1-15 км, 20-40 км і 50-60 км. Вкажіть потрібну довжину для перевірки моделі та актуальної документації." }, { question: "Пакування і маса фіксовані?", answer: "Ні. У наданих версіях посібників є неоднакові відомості. Масу, картон і експортне пакування підтверджують у пропозиції." }, { question: "Які дані потрібні для пропозиції?", answer: "Вкажіть серію або довжину, потрібний інтерфейс, кількість, країну призначення, необхідні документи та кінцеве цивільне або промислове застосування." }],
  },
  vi: {
    name: "Tang cuộn cáp quang nhả từ bên trong", shortName: "Tang cáp quang", category: "Xử lý cáp quang công nghiệp",
    description: "Tang cuộn cáp quang nhả từ bên trong cho các dự án triển khai cáp dân dụng và công nghiệp đủ điều kiện, với các dòng 1 km đến 60 km theo tài liệu được cung cấp.",
    heroCopy: "Vui lòng nêu chiều dài cần dùng, dòng tang, giao diện tích hợp, số lượng, quốc gia đến và ứng dụng dân dụng hoặc công nghiệp cuối cùng. Các thông tin này được xem xét trước báo giá.",
    seo: { title: "Tang cuộn cáp quang | Nhả từ bên trong", description: "Tang cáp quang nhả từ bên trong cho các dự án tích hợp dân dụng và công nghiệp đủ điều kiện, có tham chiếu G.657.A2 và tùy chọn 1-60 km.", keywords: ["tang cuộn cáp quang", "tang nhả từ bên trong", "cuộn sợi quang"] },
    intro: ["Tang giữ một chiều dài sợi quang đã chọn trong vỏ bảo vệ và hỗ trợ nhả cáp từ bên trong.", "Tài liệu được cung cấp mô tả ZY-SI cho 1-15 km, ZY-MI cho 20-40 km và ZY-LI cho 50-60 km. Tham chiếu công bố là sợi G.657.A2 đường kính 0.25 mm.", "Kích thước, đóng gói, khối lượng, cấu hình đầu cuối và tài liệu hiện hành được xác nhận theo từng đơn hàng. Mục đích sử dụng cuối, người dùng cuối và quốc gia đến có thể cần được xem xét tuân thủ."],
    applications: ["Lắp đặt giám sát và kiểm tra công nghiệp tạm thời", "Thử nghiệm triển khai cáp dân dụng có kiểm soát", "Dự án viễn thông và tích hợp thiết bị", "Kiểm tra hầm, đường ống và không gian kín", "Dự án hạ tầng dân dụng cố định hoặc di động đủ điều kiện"],
    faqs: [{ question: "Có những chiều dài nào?", answer: "Tài liệu nêu các dòng 1-15 km, 20-40 km và 50-60 km. Hãy nêu chiều dài cần dùng để kiểm tra mẫu và tài liệu hiện hành." }, { question: "Đóng gói và khối lượng có cố định không?", answer: "Không. Các phiên bản tài liệu được cung cấp có thông tin không đồng nhất. Khối lượng, thùng carton và đóng gói xuất khẩu được xác nhận trong báo giá." }, { question: "Cần thông tin gì để báo giá?", answer: "Hãy nêu dòng hoặc chiều dài, giao diện cần thiết, số lượng, quốc gia đến, tài liệu yêu cầu và ứng dụng dân dụng hoặc công nghiệp cuối cùng." }],
  },
  th: {
    name: "ดรัมสายเคเบิลใยแก้วนำแสงแบบจ่ายจากด้านใน", shortName: "ดรัมสายใยแก้วนำแสง", category: "การจัดการสายใยแก้วนำแสงสำหรับอุตสาหกรรม",
    description: "ดรัมสายเคเบิลใยแก้วนำแสงแบบจ่ายจากด้านในสำหรับโครงการวางสายงานโยธาและอุตสาหกรรมที่ผ่านการตรวจสอบ โดยมีรุ่น 1 km ถึง 60 km ตามคู่มือที่ให้มา",
    heroCopy: "โปรดระบุความยาวที่ต้องการ รุ่นดรัม อินเทอร์เฟซการรวมระบบ ปริมาณ ประเทศปลายทาง และการใช้งานโยธาหรืออุตสาหกรรมขั้นสุดท้าย ข้อมูลจะได้รับการตรวจสอบก่อนเสนอราคา",
    seo: { title: "ดรัมสายเคเบิลใยแก้วนำแสง | จ่ายจากด้านใน", description: "ดรัมสายเคเบิลใยแก้วนำแสงแบบจ่ายจากด้านในสำหรับโครงการรวมระบบโยธาและอุตสาหกรรมที่ผ่านการตรวจสอบ พร้อมข้อมูลอ้างอิง G.657.A2 และตัวเลือก 1-60 km", keywords: ["ดรัมสายเคเบิลใยแก้วนำแสง", "ดรัมจ่ายจากด้านใน", "ม้วนใยแก้วนำแสง"] },
    intro: ["ดรัมเก็บความยาวของใยแก้วนำแสงที่เลือกไว้ในตัวเรือนป้องกัน และรองรับการจ่ายสายจากด้านใน.", "คู่มือที่ให้มาระบุ ZY-SI สำหรับ 1-15 km, ZY-MI สำหรับ 20-40 km และ ZY-LI สำหรับ 50-60 km โดยข้อมูลอ้างอิงที่เผยแพร่คือใยแก้ว G.657.A2 ขนาด 0.25 mm.", "ขนาด บรรจุภัณฑ์ มวล การกำหนดค่าปลายสาย และเอกสารปัจจุบันจะยืนยันตามคำสั่งซื้อ การใช้งานปลายทาง ผู้ใช้ปลายทาง และประเทศปลายทางอาจต้องผ่านการตรวจสอบการปฏิบัติตามข้อกำหนด."],
    applications: ["การติดตั้งตรวจติดตามและตรวจสอบอุตสาหกรรมชั่วคราว", "การทดสอบวางสายงานโยธาแบบควบคุม", "โครงการโทรคมนาคมและการรวมระบบอุปกรณ์", "การตรวจสอบอุโมงค์ ท่อ และพื้นที่ปิด", "โครงการโครงสร้างพื้นฐานโยธาแบบอยู่กับที่หรือเคลื่อนที่ที่ผ่านการตรวจสอบ"],
    faqs: [{ question: "มีความยาวใดบ้าง?", answer: "คู่มือระบุรุ่น 1-15 km, 20-40 km และ 50-60 km โปรดแจ้งความยาวที่ต้องการเพื่อทบทวนรุ่นและเอกสารปัจจุบัน." }, { question: "บรรจุภัณฑ์และมวลเป็นค่าคงที่หรือไม่?", answer: "ไม่ใช่ คู่มือที่ให้มามีข้อมูลอ้างอิงไม่สอดคล้องกัน มวล กล่อง และบรรจุภัณฑ์ส่งออกจะยืนยันในใบเสนอราคา." }, { question: "ต้องใช้ข้อมูลใดสำหรับการเสนอราคา?", answer: "โปรดระบุรุ่นหรือความยาว อินเทอร์เฟซที่ต้องการ ปริมาณ ประเทศปลายทาง เอกสารที่ต้องการ และการใช้งานโยธาหรืออุตสาหกรรมขั้นสุดท้าย." }],
  },
};
